import { Synthesizer } from '../types';

export const rolandJV1080: Synthesizer = {
  name: 'Roland JV-1080',
  expansions: [
    {
      name: 'XpA',
      type: 'SR-JV80',
      toSelect: [
        {
          rangeHigh: 127,
          commands: [{ type: 'CC', number: 0, value: 84 }, { type: 'CC', number: 32, value: 0 }, { type: 'PC' }]
        },
        {
          rangeLow: 128,
          commands: [{ type: 'CC', number: 0, value: 84 }, { type: 'CC', number: 32, value: 1 }, { type: 'PC' }]
        }
      ]
    },
    {
      name: 'XpB',
      type: 'SR-JV80',
      toSelect: [
        {
          rangeHigh: 127,
          commands: [{ type: 'CC', number: 0, value: 84 }, { type: 'CC', number: 32, value: 2 }, { type: 'PC' }]
        },
        {
          rangeLow: 128,
          commands: [{ type: 'CC', number: 0, value: 84 }, { type: 'CC', number: 32, value: 3 }, { type: 'PC' }]
        }
      ]
    },
    {
      name: 'XpC',
      type: 'SR-JV80',
      toSelect: [
        {
          rangeHigh: 127,
          commands: [{ type: 'CC', number: 0, value: 84 }, { type: 'CC', number: 32, value: 4 }, { type: 'PC' }]
        },
        {
          rangeLow: 128,
          commands: [{ type: 'CC', number: 0, value: 84 }, { type: 'CC', number: 32, value: 5 }, { type: 'PC' }]
        }
      ]
    },
    {
      name: 'XpD',
      type: 'SR-JV80',
      toSelect: [
        {
          rangeHigh: 127,
          commands: [{ type: 'CC', number: 0, value: 84 }, { type: 'CC', number: 32, value: 6 }, { type: 'PC' }]
        },
        {
          rangeLow: 128,
          commands: [{ type: 'CC', number: 0, value: 84 }, { type: 'CC', number: 32, value: 7 }, { type: 'PC' }]
        }
      ]
    }
  ],
  banks: [
    {
      name: 'User',
      isUser: true,
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 80 }, { type: 'CC', number: 32, value: 0 }, { type: 'PC' }]
        }
      ],
      patches: [
        'Symphonique',
        'Alternative',
        'VeloTekno 1',
        'West Coast',
        'Albion',
        'Jz Gtr Hall',
        'Rocker Spin',
        '101 Bass',
        'Claviduck',
        'Jet Pad 2',
        'Raggatronic',
        'Crunch Split',
        'Running Pad',
        'Brass Sect',
        'Flying Waltz',
        'Pure Tibet',
        '4Hits4You',
        'Waterhodes',
        'Blade Racer',
        'JC Strat',
        'Dawn 2 Dusk',
        'Saw Mass',
        'Steel Away',
        '64 VoicePiano',
        'Wave Bells',
        'JP-8Haunting',
        'Vanishing',
        'Harmonica',
        'Film Octaves',
        'Edye Boost',
        'AugerMentive',
        'Deep Strings',
        'Chime Wash',
        'SA Rhodes1',
        '3D Flanged',
        'Ac.Upright',
        'Poly Brass',
        'Dissimilate',
        'Dulcimer',
        'Fantasy Vox',
        'Dist Gtr 1',
        'Sax Section',
        'Aurora',
        'St.Strings',
        'AmbienceVibe',
        'Cascade',
        'AltoLead Sax',
        'PWM Strings',
        'Childlike',
        'Velo Tekno 2',
        'Taj Mahal',
        'D-50 Stack',
        'ChamberWoods',
        'Pulse Key',
        'Mondo Bass',
        'Velo-Wah Gtr',
        'Sitar',
        'Purple Spin',
        'Random Vowels',
        'Big BPF',
        'Dunes',
        'Heirborne',
        'PsychoRhodes',
        'Tortured',
        'Bass Marimba',
        'Syncrosonix',
        'Mandolin Trem',
        'Poly Saws',
        'Pulse Pad',
        'Nylon Gtr',
        'ORBit Pad',
        'Majestic Tpt',
        'Terminate',
        'SquareLead 1',
        'House Piano',
        'Fooled Again',
        'Pick Bass',
        'Wide Tubular',
        'Velo-Rez Clv',
        'Airplaaane',
        'Delicate EP',
        'Rezoid',
        'E-Motion Pad',
        'Phripphuzz',
        'Archimede',
        'Intentions',
        'Nylon Rhodes',
        'Huff N Stuff',
        'Finger Bass',
        'Gospel Spin',
        'Harmonicum',
        'Impact',
        'Rotary Gtr',
        'Tp&Sax Sect',
        'Tubular Vox',
        'Sawteeth',
        'Ocean Floor',
        'E.Grand',
        'Clarinet mp',
        'Bass in Face',
        'Britelow Bass',
        'Mellow Bars',
        'LetterFrmPat',
        'MG Solo',
        'Air Lead',
        'Raya Shaku',
        'Greek Power',
        'Biosphere',
        'EP+Mod Pad',
        'Chambers',
        'Nomad Perc',
        'Horn Swell',
        'Hillbillys',
        'Night Shade',
        'Nice Piano',
        'VOX Flute',
        'Music Bells',
        'JUNO Strings',
        'Bs/Pno+Brs',
        'Dark Vox',
        'Bass Pizz',
        'Seq Mallet',
        'Variable Run',
        'Cyber Space',
        '12str Gtr 1',
        'PianoStrings',
        'Sands of Time',
        'Fantasia JV'
      ]
    },
    {
      name: 'PrA',
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 81 }, { type: 'CC', number: 32, value: 0 }, { type: 'PC' }]
        }
      ],
      patches: [
        '64voicePiano',
        'Bright Piano',
        'Classique',
        'Nice Piano',
        'Piano Thang',
        'Power Grand',
        'House Piano',
        'E.Grand',
        'MIDIed Grand',
        'Piano Blend',
        'West Coast',
        'PianoStrings',
        'Bs/Pno+Brs',
        'Waterhodes',
        'S.A.E.P.',
        'SA Rhodes 1',
        'SA Rhodes 2',
        'Stiky Rhodes',
        'Dig Rhodes',
        'Nylon EPiano',
        'Nylon Rhodes',
        'Rhodes Mix',
        'PsychoRhodes',
        'Tremo Rhodes',
        'MK-80 Rhodes',
        'MK-80 Phaser',
        'Delicate EP',
        'Octa Rhodes1',
        'Octa Rhodes2',
        'JV Rhodes+',
        'EP+Mod Pad',
        'Mr.Mellow',
        'Comp Clav',
        'Klavinet',
        'Winger Clav',
        'Phaze Clav 1',
        'Phaze Clav 2',
        'Phuzz Clav',
        'Chorus Clav',
        'Claviduck',
        'Velo-Rez Clv',
        'Clavicembalo',
        'Analog Clav1',
        'Analog Clav2',
        'Metal Clav',
        'Full Stops',
        'Ballad B',
        'Mellow Bars',
        'AugerMentive',
        'Perky B',
        'The Big Spin',
        'Gospel Spin',
        'Roller Spin',
        'Rocker Spin',
        'Tone Wh.Solo',
        'Purple Spin',
        '60�s LeadORG',
        'Assalt Organ',
        'D-50 Organ',
        'Cathedral',
        'Church Pipes',
        'Poly Key',
        'Poly Saws',
        'Poly Pulse',
        'Dual Profs',
        'Saw Mass',
        'Poly Split',
        'Poly Brass',
        'Stackoid',
        'Poly Rock',
        'D-50 Stack',
        'Fantasia JV',
        'Jimmee Dee',
        'Heavenals',
        'Mallet Pad',
        'Huff N Stuff',
        'Puff 1080',
        'BellVox 1080',
        'Fantasy Vox',
        'Square Keys',
        'Childlike',
        'Music Box',
        'Toy Box',
        'Wave Bells',
        'Tria Bells',
        'Beauty Bells',
        'Music Bells',
        'Pretty Bells',
        'Pulse Key',
        'Wide Tubular',
        'AmbienceVibe',
        'Warm Vibes',
        'Dyna Marimba',
        'Bass Marimba',
        'Nomad Perc',
        'Ethno Metals',
        'Islands Mlt',
        'Steelin Keys',
        'Steel Drums',
        'Voicey Pizz',
        'Sitar',
        'Drone Split',
        'Ethnopluck',
        'Jamisen',
        'Dulcimer',
        'East Melody',
        'MandolinTrem',
        'Nylon Gtr',
        'Gtr Strings',
        'Steel Away',
        'Heavenly Gtr',
        '12str Gtr 1',
        '12str Gtr 2',
        'Jz Gtr Hall',
        'LetterFrmPat',
        'Jazz Scat',
        'Lounge Gig',
        'JC Strat',
        'Twin Strats',
        'JV Strat',
        'Syn Strat',
        'Rotary Gtr',
        'Muted Gtr',
        'SwitchOnMute',
        'Power Trip',
        'Crunch Split',
        'Rezodrive',
        'RockYurSocks'
      ]
    },
    {
      name: 'PrB',
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 81 }, { type: 'CC', number: 32, value: 1 }, { type: 'PC' }]
        }
      ],
      patches: [
        'Dist Gtr 1',
        'Dist Gtr 2',
        'R&R Chunk',
        'Phripphuzz',
        'Grungeroni',
        'Black Widow',
        'Velo-Wah Gtr',
        'Mod-Wah Gtr',
        'Pick Bass',
        'Hip Bass',
        'Perc.Bass',
        'Homey Bass',
        'Finger Bass',
        'Nylon Bass',
        'Ac.Upright',
        'Wet Fretls',
        'Fretls Dry',
        'Slap Bass 1',
        'Slap Bass 2',
        'Slap Bass 3',
        'Slap Bass 4',
        '4 Pole Bass',
        'Tick Bass',
        'House Bass',
        'Mondo Bass',
        'Clk AnalogBs',
        'Bass In Face',
        '101 Bass',
        'Noiz Bass',
        'Super Jup Bs',
        'Occitan Bass',
        'Hugo Bass',
        'Multi Bass',
        'Moist Bass',
        'BritelowBass',
        'Untamed Bass',
        'Rubber Bass',
        'Stereoww Bs',
        'Wonder Bass',
        'Deep Bass',
        'Super JX Bs',
        'W<RED>-Bass',
        'HI-Ring Bass',
        'Euro Bass',
        'SinusoidRave',
        'Alternative',
        'Acid Line',
        'Auto TB-303',
        'Hihat Tekno',
        'Velo Tekno 1',
        'Raggatronic',
        'Blade Racer',
        'S&H Pad',
        'Syncrosonix',
        'Fooled Again',
        'Alive',
        'Velo Tekno 2',
        'Rezoid',
        'Raverborg',
        'Blow Hit',
        'Hammer Bell',
        'Seq Mallet',
        'Intentions',
        'Pick It',
        'Analog Seq',
        'Impact Vox',
        'TeknoSoloVox',
        'X-Mod Man',
        'Paz <==> Zap',
        '4Hits4You',
        'Impact',
        'Phase Hit',
        'Tekno Hit 1',
        'Tekno Hit 2',
        'Tekno Hit 3',
        'Reverse Hit',
        'SquareLead 1',
        'SquareLead 2',
        'You and Luck',
        'Belly Lead',
        'WhistlinAtom',
        'Edye Boost',
        'MG Solo',
        'FXM Saw Lead',
        'Sawteeth',
        'Smoothe',
        'MG Lead',
        'MG Interval',
        'Pulse Lead 1',
        'Pulse Lead 2',
        'Little Devil',
        'Loud SynLead',
        'Analog Lead',
        '5th Lead',
        'Flute',
        'Piccolo',
        'VOX Flute',
        'Air Lead',
        'Pan Pipes',
        'Airplaaane',
        'Taj Mahal',
        'Raya Shaku',
        'Oboe mf',
        'Oboe Express',
        'Clarinet mp',
        'ClariExpress',
        'Mitzva Split',
        'ChamberWinds',
        'ChamberWoods',
        'Film Orch',
        'Sop.Sax mf',
        'Alto Sax',
        'AltoLead Sax',
        'Tenor Sax',
        'Baritone Sax',
        'Take A Tenor',
        'Sax Section',
        'Bigband Sax',
        'Harmonica',
        'Harmo Blues',
        'BluesHarp',
        'Hillbillys',
        'French Bags',
        'Majestic Tpt',
        'Voluntare',
        '2Trumpets',
        'Tpt Sect',
        'Mute TP mod'
      ]
    },
    {
      name: 'PrC',
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 81 }, { type: 'CC', number: 32, value: 2 }, { type: 'PC' }]
        }
      ],
      patches: [
        'Harmon Mute',
        'Tp&Sax Sect',
        'Sax+Tp+Tb',
        'Brass Sect',
        'Trombone',
        'Hybrid Bones',
        'Noble Horns',
        'Massed Horns',
        'Horn Swell',
        'Brass It!',
        'Brass Attack',
        'Archimede',
        'Rugby Horn',
        'MKS-80 Brass',
        'True ANALOG',
        'Dark Vox',
        'RandomVowels',
        'Angels Sing',
        'Pvox Oooze',
        'Longing...',
        'Arasian Morn',
        'Beauty Vox',
        'Mary-AnneVox',
        'Belltree Vox',
        'Vox Panner',
        'Spaced Voxx',
        'Glass Voices',
        'Tubular Vox',
        'Velo Voxx',
        'Wavox',
        'Doos',
        'Synvox Comps',
        'Vocal Oohz',
        'LFO Vox',
        'St.Strings',
        'Warm Strings',
        'Somber Str',
        'Marcato',
        'Bright Str',
        'String Ens',
        'TremoloStrng',
        'Chambers',
        'ViolinCello',
        'Symphonique',
        'Film Octaves',
        'Film Layers',
        'Bass Pizz',
        'Real Pizz',
        'Harp On It',
        'Harp',
        'JP-8 Str 1',
        'JP-8 Str 2',
        'E-Motion Pad',
        'JP-8 Str 3',
        'Vintage Orch',
        'JUNO Strings',
        'Gigantalog',
        'PWM Strings',
        'Warmth',
        'ORBit Pad',
        'Deep Strings',
        'Pulsify',
        'Pulse Pad',
        'Greek Power',
        'Harmonicum',
        'D-50 Heaven',
        'Afro Horns',
        'Pop Pad',
        'Dreamesque',
        'Square Pad',
        'JP-8 Hollow',
        'JP-8Haunting',
        'Heirborne',
        'Hush Pad',
        'Jet Pad 1',
        'Jet Pad 2',
        'Phaze Pad',
        'Phaze Str',
        'Jet Str Ens',
        'Pivotal Pad',
        '3D Flanged',
        'Fantawine',
        'Glassy Pad',
        'Moving Glass',
        'Glasswaves',
        'Shiny Pad',
        'ShiftedGlass',
        'Chime Pad',
        'Spin Pad',
        'Rotary Pad',
        'Dawn 2 Dusk',
        'Aurora',
        'Strobe Mode',
        'Albion',
        'Running Pad',
        'Stepped Pad',
        'Random Pad',
        'SoundtrkDANC',
        'Flying Waltz',
        'Vanishing',
        '5th Sweep',
        'Phazweep',
        'Big BPF',
        'MG Sweep',
        'CeremonyTimp',
        'Dyno Toms',
        'Sands ofTime',
        'Inertia',
        'Vektogram',
        'Crash Pad',
        'Feedback VOX',
        'Cascade',
        'Shattered',
        'NextFrontier',
        'Pure Tibet',
        'Chime Wash',
        'Night Shade',
        'Tortured',
        'Dissimilate',
        'Dunes',
        'Ocean Floor',
        'Cyber Space',
        'Biosphere',
        'Variable Run',
        'Ice Hall',
        'ComputerRoom',
        'Inverted',
        'Terminate'
      ]
    },
    {
      name: 'PrD',
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 81 }, { type: 'CC', number: 32, value: 3 }, { type: 'PC' }]
        }
      ],
      patches: [
        'Acoustic Grand Piano',
        'Bright Acoustic Piano',
        'Electric Grand Piano',
        'Honky-tonk Piano',
        'Rhodes Piano',
        'Chorused Electric Piano',
        'Harpsichord',
        'Clavinet',
        'Celesta',
        'Glockenspiel',
        'Music Box',
        'Vibraphone',
        'Marimba',
        'Xylophone',
        'Tubular Bell',
        'Santur',
        'Hammond Organ',
        'Percussive Organ',
        'Rock Organ',
        'Church Organ 1',
        'Reed Organ',
        'French Accordion',
        'Harmonica',
        'Bandoneon',
        'Nylon-String Guitar',
        'Steel-String Guitar',
        'Jazz Guitar',
        'Clean Electric Guitar',
        'Muted Electric Guitar',
        'Overdriven Guitar',
        'Distortion Guitar',
        'Guitar Harmonics',
        'Acoustic Bass',
        'Fingered Bass',
        'Picked Bass',
        'Fretless Bass',
        'Slap Bass 1',
        'Slap Bass 2',
        'Synth Bass 1',
        'Synth Bass 2',
        'Violin',
        'Viola',
        'Cello',
        'Contrabass',
        'Tremolo Strings',
        'Pizzicato Strings',
        'Harp',
        'Timpani',
        'String Ensemble',
        'Slow String Ensemble',
        'Synth Strings 1',
        'Synth Strings 2',
        'Choir Aahs',
        'Voice Oohs',
        'Synth Voice',
        'Orchestra Hit',
        'Trumpet',
        'Trombone',
        'Tuba',
        'Muted Trumpet',
        'French Horns',
        'Brass Section 1',
        'Synth Brass 1',
        'Synth Brass 2',
        'Soprano Sax',
        'Alto Sax',
        'Tenor Sax',
        'Baritone Sax',
        'Oboe',
        'English Horn',
        'Bassoon',
        'Clarinet',
        'Piccolo',
        'Flute',
        'Recorder',
        'Pan Flute',
        'Bottle Blow',
        'Shakuhachi',
        'Whistle',
        'Ocarina',
        'Square Lead',
        'Saw Lead',
        'Synth Calliope',
        'Chiffer Lead',
        'Charang',
        'Solo Synth Vox',
        '5th Saw Wave',
        'Bass & Lead',
        'Fantasia Pad',
        'Warm Pad',
        'Polysynth Pad',
        'Space Voice Pad',
        'Bowed Glass Pad',
        'Metal Pad',
        'Halo Pad',
        'Sweep Pad',
        'Ice Rain',
        'Soundtrack',
        'Crystal',
        'Atmosphere',
        'Brightness',
        'Goblin',
        'Echo Drops',
        'Star Theme',
        'Sitar',
        'Banjo',
        'Shamisen',
        'Koto',
        'Kalimba',
        'Bagpipe',
        'Fiddle',
        'Shanai',
        'Tinkle Bell',
        'Agogo',
        'Steel Drums',
        'Woodblock',
        'Taiko',
        'Melodic Tom 1',
        'Synth Drum',
        'Reverse Cymbal',
        'Guitar Fret Noise',
        'Breath Noise',
        'Seashore',
        'Bird',
        'Telephone 1',
        'Helicopter',
        'Applause',
        'Gun Shot'
      ]
    }
  ]
};
