import { Synthesizer } from '../types';

export const rolandXV3080: Synthesizer = {
  name: 'Roland XV-3080',
  expansions: [
    {
      name: 'XpA',
      type: 'SR-JV80',
      toSelect: 'SELECT_BY_CARD'
    },
    {
      name: 'XpB',
      type: 'SR-JV80',
      toSelect: 'SELECT_BY_CARD'
    },
    {
      name: 'XpC',
      type: 'SR-JV80',
      toSelect: 'SELECT_BY_CARD'
    },
    {
      name: 'XpD',
      type: 'SR-JV80',
      toSelect: 'SELECT_BY_CARD'
    },
    {
      name: 'XpE',
      type: 'SRX',
      toSelect: 'SELECT_BY_CARD'
    },
    {
      name: 'XpF',
      type: 'SRX',
      toSelect: 'SELECT_BY_CARD'
    }
  ],
  banks: [
    {
      name: 'User',
      isUser: true,
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 87 }, { type: 'CC', number: 32, value: 0 }, { type: 'PC' }]
        }
      ],
      patches: [
        'Y2K Concerto',
        'XV SteelGt 1',
        'Shapeshifter',
        'Trance Fair ',
        'MOVE!',
        'VoyagerBrass',
        'Rholitzer',
        'Grand XV',
        'Pianomonics',
        'Nylozzicato',
        'Searing Lead',
        'Square Roots',
        'Winky',
        'Atmospherics',
        'Soft Perky',
        'NewR&RBrass',
        'Lunar Strngs',
        'LegatoBamboo',
        'West End Bs',
        'Marcato Str',
        'Henry VIII',
        'Chime Bells',
        'Morph Pad',
        'Dirty Hit',
        'Soaring Hrns',
        'XV Ac.Bass',
        'Grounded Bs',
        'Severe Ow Bs',
        'Celtic Harp',
        'XV Strings',
        'Air Pad',
        'Hit Rhodes',
        'The Beast',
        'SteppingPhsr',
        'LivingInSync',
        'PhazeWahClav',
        'Rippling',
        'Rhodes Trem',
        'Rocker Org',
        'Cutter>ModWh',
        'Queen V',
        "Flyin' High",
        'Soft Nylon',
        "Don't Jump",
        'RockPiano Ch',
        'St. Choir',
        'Galactic',
        'Phaser Dyno',
        'Andreas Cave',
        'ChmbrQuartet',
        "Plug n' Play",
        'Agent X',
        'Lo-fi Sweep',
        '2ndRateChord',
        'Creamy Bass',
        'Phunky DC',
        'Suite Combo',
        'JupiterHorns',
        'Talking Box',
        'Piano+SftPad',
        '8VCO MonoSyn',
        'Double Steel',
        'Cutter Clav',
        'Prelude',
        'Wurlie',
        'TB Squelch',
        'The Ganges',
        'British B',
        'Power Stack',
        'Predator 2',
        'Moonchimes',
        'Ooh)Aah Mod',
        'PercInterval',
        'Vocals: Boys',
        'Fat Strings',
        'Str&Brs Orch',
        'ChamberPlyrs',
        'Glass Orbit',
        'The Andes',
        'ClassicJPpad',
        'FullSt Brass',
        'Punker',
        'Pop Bass',
        'Solo SoprSax',
        'Fat Rhodes',
        'X-mod Sweep',
        'XV DynoTenor',
        'Hybrid Nylon',
        'SquareBounce',
        "8-str F'less",
        'Big Bubbles',
        'SampleThe80s',
        'BOG',
        '96 Years',
        'LookMaNoFret',
        'X-mod Reso',
        'SkinnyBounce',
        'Tap Bass',
        'Brite Vox 1',
        'Brass Tubes',
        '80s Retrosyn',
        'MountainFolk',
        'Soaring Sync',
        'Analogical',
        'MinorIncidnt',
        'Slap Timps',
        "Comp'Steel",
        'Reel Slam',
        'Adrenaline',
        'Choir Bounce',
        'Jet Voxs',
        'Halographix',
        '3PartInventn',
        'Retro Rhodes',
        'Slap Bass 3',
        'Guttural',
        'Blades',
        'Nasal Spray',
        'Synergistic',
        'Dragnet',
        '5th Atm /Aft',
        'AmbiPizza',
        'GR700 Pad',
        'Tape Strings',
        'Soaring Saws',
        'Temple of JV',
        'Alternative',
        'Sun Dive'
      ]
    },
    {
      name: 'PrA',
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 87 }, { type: 'CC', number: 32, value: 64 }, { type: 'PC' }]
        }
      ],
      patches: [
        '128voicePno',
        'Bright Piano',
        'Classique',
        'Nice Piano',
        'Piano Thang',
        'Power Grand',
        'House Piano',
        'E.Grand',
        'MIDIed Grand',
        'Piano Blend',
        'West Coast',
        'PianoStrings',
        'Bs/Pno+Brs',
        'Waterhodes',
        'S.A.E.P.',
        'SA Rhodes 1',
        'SA Rhodes 2',
        'Stiky Rhodes',
        'Dig Rhodes',
        'Nylon EPiano',
        'Nylon Rhodes',
        'Rhodes Mix',
        'PsychoRhodes',
        'Tremo Rhodes',
        'MK-80 Rhodes',
        'MK-80 Phaser',
        'Delicate EP',
        'Octa Rhodes1',
        'Octa Rhodes2',
        'JV Rhodes+',
        'EP+Mod Pad',
        'Mr.Mellow',
        'Comp Clav',
        'Klavinet',
        'Winger Clav',
        'Phaze Clav 1',
        'Phaze Clav 2',
        'Phuzz Clav',
        'Chorus Clav',
        'Claviduck',
        'Velo-Rez Clv',
        'Clavicembalo',
        'Analog Clav1',
        'Analog Clav2',
        'Metal Clav',
        'Full Stops',
        'Ballad B',
        'Mellow Bars',
        'AugerMentive',
        'Perky B',
        'The Big Spin',
        'Gospel Spin',
        'Roller Spin',
        'Rocker Spin',
        'Tone Wh.Solo',
        'Purple Spin',
        "60's LeadORG",
        'Assalt Organ',
        'D-50 Organ',
        'Cathedral',
        'Church Pipes',
        'Poly Key',
        'Poly Saws',
        'Poly Pulse',
        'Dual Profs',
        'Saw Mass',
        'Poly Split',
        'Poly Brass',
        'Stackoid',
        'Poly Rock',
        'D-50 Stack',
        'Fantasia JV',
        'Jimmee Dee',
        'Heavenals',
        'Mallet Pad',
        'Huff N Stuff',
        'Puff 1080',
        'BellVox 1080',
        'Fantasy Vox',
        'Square Keys',
        'Childlike',
        'Music Box',
        'Toy Box',
        'Wave Bells',
        'Tria Bells',
        'Beauty Bells',
        'Music Bells',
        'Pretty Bells',
        'Pulse Key',
        'Wide Tubular',
        'AmbienceVibe',
        'Warm Vibes',
        'Dyna Marimba',
        'Bass Marimba',
        'Nomad Perc',
        'Ethno Metals',
        'Islands Mlt',
        'Steelin Keys',
        'Steel Drums',
        'Voicey Pizz',
        'Sitar',
        'Drone Split',
        'Ethnopluck',
        'Jamisen',
        'Dulcimer',
        'East Melody',
        'MandolinTrem',
        'Nylon Gtr',
        'Gtr Strings',
        'Steel Away',
        'Heavenly Gtr',
        '12str Gtr 1',
        '12str Gtr 2',
        'Jz Gtr Hall',
        'LetterFrmPat',
        'Jazz Scat',
        'Lounge Gig',
        'JC Strat',
        'Twin Strats',
        'JV Strat',
        'Syn Strat',
        'Rotary Gtr',
        'Muted Gtr',
        'SwitchOnMute',
        'Power Trip',
        'Crunch Split',
        'Rezodrive',
        'RockYurSocks'
      ]
    },
    {
      name: 'PrB',
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 87 }, { type: 'CC', number: 32, value: 65 }, { type: 'PC' }]
        }
      ],
      patches: [
        'Dist Gtr 1',
        'Dist Gtr 2',
        'R&R Chunk',
        'Phripphuzz',
        'Grungeroni',
        'Black Widow',
        'Velo-Wah Gtr',
        'Mod-Wah Gtr',
        'Pick Bass',
        'Hip Bass',
        'Perc.Bass',
        'Homey Bass',
        'Finger Bass',
        'Nylon Bass',
        'Ac.Upright',
        'Wet Fretls',
        'Fretls Dry',
        'Slap Bass 1',
        'Slap Bass 2',
        'Slap Bass 3',
        'Slap Bass 4',
        '4 Pole Bass',
        'Tick Bass',
        'House Bass',
        'Mondo Bass',
        'Clk AnalogBs',
        'Bass In Face',
        '101 Bass',
        'Noiz Bass',
        'Super Jup Bs',
        'Occitan Bass',
        'Hugo Bass',
        'Multi Bass',
        'Moist Bass',
        'BritelowBass',
        'Untamed Bass',
        'Rubber Bass',
        'Stereoww Bs',
        'Wonder Bass',
        'Deep Bass',
        'Super JX Bs',
        'W<RED>-Bass',
        'HI-Ring Bass',
        'Euro Bass',
        'SinusoidRave',
        'Alternative',
        'Acid Line',
        'Auto TB-303',
        'Hihat Tekno',
        'Velo Tekno 1',
        'Raggatronic',
        'Blade Racer',
        'S&H Pad',
        'Syncrosonix',
        'Fooled Again',
        'Alive',
        'Velo Tekno 2',
        'Rezoid',
        'Raverborg',
        'Blow Hit',
        'Hammer Bell',
        'Seq Mallet',
        'Intentions',
        'Pick It',
        'Analog Seq',
        'Impact Vox',
        'TeknoSoloVox',
        'X-Mod Man',
        'Paz <==> Zap',
        '4 Hits 4 You',
        'Impact',
        'Phase Hit',
        'Tekno Hit 1',
        'Tekno Hit 2',
        'Tekno Hit 3',
        'Reverse Hit',
        'SquareLead 1',
        'SquareLead 2',
        'You and Luck',
        'Belly Lead',
        'WhistlinAtom',
        'Edye Boost',
        'MG Solo',
        'FXM Saw Lead',
        'Sawteeth',
        'Smoothe',
        'MG Lead',
        'MG Interval',
        'Pulse Lead 1',
        'Pulse Lead 2',
        'Little Devil',
        'Loud SynLead',
        'Analog Lead',
        '5th Lead',
        'Flute',
        'Piccolo',
        'VOX Flute',
        'Air Lead',
        'Pan Pipes',
        'Airplaaane',
        'Taj Mahal',
        'Raya Shaku',
        'Oboe mf',
        'Oboe Express',
        'Clarinet mp',
        'ClariExpress',
        'Mitzva Split',
        'ChamberWinds',
        'ChamberWoods',
        'Film Orch',
        'Sop.Sax mf',
        'Alto Sax',
        'AltoLead Sax',
        'Tenor Sax',
        'Baritone Sax',
        'Take A Tenor',
        'Sax Section',
        'Bigband Sax',
        'Harmonica',
        'Harmo Blues',
        'BluesHarp',
        'Hillbillys',
        'French Bags',
        'Majestic Tpt',
        'Voluntare',
        '2Trumpets',
        'Tpt Sect',
        'Mute TP mod'
      ]
    },
    {
      name: 'PrC',
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 87 }, { type: 'CC', number: 32, value: 66 }, { type: 'PC' }]
        }
      ],
      patches: [
        'Harmon Mute',
        'Tp&Sax Sect',
        'Sax+Tp+Tb',
        'Brass Sect',
        'Trombone',
        'Hybrid Bones',
        'Noble Horns',
        'Massed Horns',
        'Horn Swell',
        'Brass It!',
        'Brass Attack',
        'Archimede',
        'Rugby Horn',
        'MKS-80 Brass',
        'True ANALOG',
        'Dark Vox',
        'RandomVowels',
        'Angels Sing',
        'Pvox Oooze',
        'Longing...',
        'Arasian Morn',
        'Beauty Vox',
        'Mary-AnneVox',
        'Belltree Vox',
        'Vox Panner',
        'Spaced Voxx',
        'Glass Voices',
        'Tubular Vox',
        'Velo Voxx',
        'Wavox',
        'Doos',
        'Synvox Comps',
        'Vocal Oohz',
        'LFO Vox',
        'St.Strings',
        'Warm Strings',
        'Somber Str',
        'Marcato',
        'Bright Str',
        'String Ens',
        'TremoloStrng',
        'Chambers',
        'ViolinCello',
        'Symphonique',
        'Film Octaves',
        'Film Layers',
        'Bass Pizz',
        'Real Pizz',
        'Harp On It',
        'Harp',
        'JP-8 Str 1',
        'JP-8 Str 2',
        'E-Motion Pad',
        'JP-8 Str 3',
        'Vintage Orch',
        'JUNO Strings',
        'Gigantalog',
        'PWM Strings',
        'Warmth',
        'ORBit Pad',
        'Deep Strings',
        'Pulsify',
        'Pulse Pad',
        'Greek Power',
        'Harmonicum',
        'D-50 Heaven',
        'Afro Horns',
        'Pop Pad',
        'Dreamesque',
        'Square Pad',
        'JP-8 Hollow',
        'JP-8Haunting',
        'Heirborne',
        'Hush Pad',
        'Jet Pad 1',
        'Jet Pad 2',
        'Phaze Pad',
        'Phaze Str',
        'Jet Str Ens',
        'Pivotal Pad',
        '3D Flanged',
        'Fantawine',
        'Glassy Pad',
        'Moving Glass',
        'Glasswaves',
        'Shiny Pad',
        'ShiftedGlass',
        'Chime Pad',
        'Spin Pad',
        'Rotary Pad',
        'Dawn 2 Dusk',
        'Aurora',
        'Strobe Mode',
        'Albion',
        'Running Pad',
        'Stepped Pad',
        'Random Pad',
        'SoundtrkDANC',
        'Flying Waltz',
        'Vanishing',
        '5th Sweep',
        'Phazweep',
        'Big BPF',
        'MG Sweep',
        'CeremonyTimp',
        'Dyno Toms',
        'Sands ofTime',
        'Inertia',
        'Vektogram',
        'Crash Pad',
        'Feedback VOX',
        'Cascade',
        'Shattered',
        'NextFrontier',
        'Pure Tibet',
        'Chime Wash',
        'Night Shade',
        'Tortured',
        'Dissimilate',
        'Dunes',
        'Ocean Floor',
        'Cyber Space',
        'Biosphere',
        'Variable Run',
        'Ice Hall',
        'ComputerRoom',
        'Inverted',
        'Terminate'
      ]
    },
    {
      name: 'PrD',
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 87 }, { type: 'CC', number: 32, value: 67 }, { type: 'PC' }]
        }
      ],
      patches: [
        'Echo Piano',
        'Upright Pno',
        'RD-1000',
        "Player's EP",
        'D-50 Rhodes',
        'Innocent EP',
        'Echo Rhodes',
        'See-Thru EP',
        'FM BellPiano',
        'Ring E.Piano',
        'Soap Opera',
        'Dirty Organ',
        "Surf's Up!",
        'Organesque',
        'pp Harmonium',
        'PieceOfCheez',
        'Harpsy Clav',
        'Exotic Velo',
        'HolidayCheer',
        'Morning Lite',
        'Prefab Chime',
        'Belfry Chime',
        'Stacc.Heaven',
        '2.2 Bell Pad',
        'Far East',
        'Wire Pad',
        'PhaseBlipper',
        'Sweep Clav',
        'Glider',
        'Solo Steel',
        'DesertCrystl',
        'Clear Guitar',
        'Solo Strat',
        'Feed Me!',
        'Tube Smoke',
        'Creamy',
        'Blusey OD',
        'Grindstone',
        'OD 5ths',
        'East Europe',
        'Dulcitar',
        'Atmos Harp',
        'Pilgrimage',
        '202 Rude Bs',
        '2pole Bass',
        '4pole Bass',
        'Phaser MC',
        'Miniphaser',
        'Acid TB',
        'Full Orchest',
        'Str + Winds',
        'Flute 2080',
        'Scat Flute',
        'Sax Choir',
        'Ballad Trump',
        'Sm.Brass Grp',
        'Royale',
        'Brass Mutes',
        'Breathy Brs',
        '3 Osc Brass',
        'P5 Polymod',
        'Triumph Brs',
        'Techno Dream',
        'Organizer',
        'Civilization',
        'Mental Chord',
        'House Chord',
        'Sequalog',
        'Booster Bips',
        'VintagePlunk',
        'Plik-Plok',
        'RingSequence',
        'Cyber Swing',
        'Keep :-)',
        'Resojuice',
        "B'on d'moov!",
        'Dist TB-303',
        'Temple of JV',
        'Planet Asia',
        'Afterlife',
        'Trancing Pad',
        'Pulsatronic',
        'Cyber Dreams',
        'Warm Pipe',
        'Pure Pipe',
        'SH-2000',
        'X..? Whistle',
        'Jay Vee Solo',
        'Progresso Ld',
        'Adrenaline',
        'Enlighten',
        'Glass Blower',
        'Earth Blow',
        'JX SqrCarpet',
        'Dimensional',
        'Jupiterings',
        'Analog Drama',
        'Rich Dynapad',
        'Silky Way',
        'Gluey Pad',
        'BandPass Mod',
        'Soundtraque',
        'Translucence',
        'Darkshine',
        "D'light",
        'December Sky',
        'Octapad',
        'JUNO Power!',
        'Spectrum Mod',
        'Stringsheen',
        'GR500 TmpDly',
        'Mod DirtyWav',
        'Silicon Str',
        'D50FantaPerc',
        'Rotodreams',
        'Blue Notes',
        'RiversOfTime',
        'Phobos',
        '2 0 8 0',
        'Unearthly',
        'Glistening',
        'Sci-Fi Str',
        'Shadows',
        'Helium Queen',
        'Sci-Fi FX x4',
        'Perky Noize',
        'Droplet',
        'Rain Forest'
      ]
    },
    {
      name: 'PrE',
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 87 }, { type: 'CC', number: 32, value: 68 }, { type: 'PC' }]
        }
      ],
      patches: [
        'Grand XV',
        'Contemplate',
        'Rock Piano',
        'RockPiano Ch',
        'Pianomonics',
        'Piano+SftPad',
        'WarmVoxPiano',
        'Y2K Concerto',
        'Piano+AirPad',
        'ChoraLeader',
        'SparklePiano',
        'Retro Rhodes',
        'Fat Rhodes',
        'Rhodes Trem',
        'Phaser Dyno',
        'Hit Rhodes',
        'Sweet Tynes',
        'Pluk Rhodes',
        'Rhodes Trip',
        'AmbiRhodes',
        'Rholitzer',
        'Wurlie',
        'FM Delight',
        'Cutter Clav',
        'Mute Clav D6',
        'PhazeWahClav',
        'St.Harpsichd',
        '3PartInventn',
        'Soft Perky',
        'Fullness',
        'Paleface 1',
        'Paleface 2',
        'Soft B',
        'British B',
        'Rocker Org',
        'Split B',
        'PercInterval',
        'Happy 60s',
        '96 Years',
        'Glory Us Rok',
        'Church Harmn',
        'Cathdr Harmn',
        'Morph Pad',
        'Air Pad',
        'Soft Padding',
        'Warmth Pad',
        'ClassicJPpad',
        'Jupiter Str',
        'Fat Pad',
        'GR700 Pad',
        'Paradise',
        'Moonchimes',
        'SusPed Swap',
        'PhasingPad',
        'Ethereal Str',
        'Velcropad',
        'NothrnLights',
        'Sun Dive',
        'Brite Vox 1',
        'Brite Vox 2',
        'Ooh)Aah Mod',
        'Vocals: Ooh',
        'Vocals: Scat',
        'Vocals: Boys',
        'St. Choir',
        'SampleThe80s',
        'Sacred Tree',
        'VP330 OctEko',
        'XV Strings',
        'Fat Strings',
        'Dolce p/m/f',
        'Sad Strings',
        'Lush Strings',
        'Strings4Film',
        'Marcato Str',
        'End Titles',
        'ChmbrQuartet',
        'ChamberSect.',
        'FullChmbrStr',
        'Tape Strings',
        'Henry VIII',
        'Prelude',
        'Str&Brs Orch',
        'Hornz',
        'TudorFanfare',
        'ChamberPlyrs',
        'Flute/Clari',
        'Orch Reeds',
        'Dual Flutes',
        'Jazzer Flute',
        'LegatoBamboo',
        'Ambience Flt',
        'The Andes',
        'Deja Vlute',
        'Simply Brass',
        'FullSt Brass',
        'Dragnet',
        'NewR&RBrass',
        'Tower Trumps',
        'BigBrassBand',
        "Lil'BigHornz",
        'VoyagerBrass',
        'Symph Horns',
        'Trombone Atm',
        'XV Trombone',
        'XV Trumpet',
        'JupiterHorns',
        'Solo SoprSax',
        'Solo AltoSax',
        'XV DynoTenor',
        'Honker Bari',
        'Full Saxz',
        'Soaring Hrns',
        'Glass Orbit',
        '5th Atm /Aft',
        'Lo-fi Sweep',
        'Modular Life',
        'Oscillations',
        'Combing',
        'Rolling 5ths',
        'Analogue Str',
        'Lunar Strngs',
        'BPFsweep Mod',
        'Queen V',
        'SkinnyBounce',
        'SquareBounce',
        'Galactic',
        'Powerwiggle'
      ]
    },
    {
      name: 'PrF',
      toSelect: [
        {
          commands: [{ type: 'CC', number: 0, value: 87 }, { type: 'CC', number: 32, value: 69 }, { type: 'PC' }]
        }
      ],
      patches: [
        '80s Retrosyn',
        'Power Stack',
        "Don't Jump",
        'Big Bubbles',
        'X-mod Sweep',
        "Bag O' Bones",
        'AirSoThin',
        'Analogical',
        'Waspy Pulse',
        'Soaring Saws',
        'Square Roots',
        'BOG',
        'Talking Box',
        'Retro Lead',
        'LivingInSync',
        'Leads United',
        'Dirty Sync',
        'DistortaSync',
        'Blistering',
        'Guttural',
        "Flyin' High",
        'Soft Tooth',
        'Soaring Sqr',
        'Soaring Sync',
        'Nasal Spray',
        'Lamb Lead',
        'Creamer',
        'Sine System',
        'Soft Nylon',
        'Nylozzicato',
        'Mutezzicato',
        'Hybrid Nylon',
        'XV SteelGt 1',
        'XV SteelGt 2',
        "Comp'Steel",
        'Double Steel',
        'Folk Guitar',
        'SpanishNight',
        "Plug n' Play",
        'Fab 4 Guitar',
        'Searing Lead',
        'Punker',
        'LouderPlease',
        'XV Upright',
        'XV Ac.Bass',
        'LookMaNoFret',
        'XV Fretless',
        "Basic F'less",
        "8-str F'less",
        'Tap Bass',
        'Pop Bass',
        'P.Bs Chorus',
        'TremCho Bs',
        'Creamy Bass',
        'Buster Bass',
        'TB Squelch',
        'Ticker Bass',
        'Muscle Bass',
        'Grounded Bs',
        'West End Bs',
        'Snap Bass',
        '700 Bassboy',
        '8VCO MonoSyn',
        'ResoMoist Bs',
        "Kickin' Bass",
        'Sub Zero',
        'Liquid Bass',
        'Hefty Bass',
        'Severe Ow Bs',
        'Chime Bells',
        'Celestabox',
        'Brass Tubes',
        'Dreams East',
        'Synergistic',
        'Andreas Cave',
        'AmbiPizza',
        'Voxy Nylon',
        'EastrnEurope',
        'Celtic Harp',
        'Reso Sitar',
        'The Ganges',
        'MountainFolk',
        'Byzantine',
        'AsiaPlectrum',
        'VelHarp)Harm',
        'Pluckaphone',
        'Slap Timps',
        'Suite Combo',
        'Jet Voxs',
        'Dirty Hit',
        'MOVE!',
        'Reel Slam',
        'OffTheRecord',
        '2ndRateChord',
        'RageInYouth',
        'MinorIncidnt',
        'Phunky DC',
        'Agent X',
        'Winky',
        'Looney 2nz',
        'Shortrave',
        'DeeperBeeper',
        'Percolator',
        'Filter Morph',
        'Choir Bounce',
        'Rippling',
        'SteppingPhsr',
        'Trance Fair',
        'GermanBounce',
        'Acid JaZZ',
        'Cutter>ModWh',
        'Blades',
        'Mad Bender',
        'Shapeshifter',
        'ForestMoon',
        'Predator 2',
        'Dark Side',
        'The Beast',
        'X-mod Reso',
        'Planet Meta',
        'Nexus',
        'Halographix',
        'Moon Rise',
        'Gruvacious',
        'Windy Dunes',
        'Ice Blasts',
        'Ringy Thingy',
        'Atmospherics'
      ]
    },
    'GM2'
  ],
  cardSelectors: {
    'SR-JV80-01': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 0 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 1 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-02': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 2 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 3 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-03': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 4 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 5 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-04': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 6 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 7 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-05': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 8 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 9 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-06': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 10 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 11 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-07': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 12 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 13 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-08': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 14 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 15 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-09': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 16 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 17 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-10': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 18 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 19 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-11': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 20 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 21 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-12': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 22 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 23 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-13': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 24 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 25 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-14': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 26 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 27 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-15': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 28 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 29 }, { type: 'PC' }]
      }
    ],
    'SR-JV80-16': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 30 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        commands: [{ type: 'CC', number: 0, value: 89 }, { type: 'CC', number: 32, value: 31 }, { type: 'PC' }]
      }
    ],
    'SRX-01': [
      {
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 0 }, { type: 'PC' }]
      }
    ],
    'SRX-02': [
      {
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 1 }, { type: 'PC' }]
      }
    ],
    'SRX-03': [
      {
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 2 }, { type: 'PC' }]
      }
    ],
    'SRX-04': [
      {
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 3 }, { type: 'PC' }]
      }
    ],
    'SRX-05': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 4 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        rangeHigh: 255,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 5 }, { type: 'PC' }]
      },
      {
        rangeLow: 256,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 6 }, { type: 'PC' }]
      }
    ],
    'SRX-06': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 7 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        rangeHigh: 255,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 8 }, { type: 'PC' }]
      },
      {
        rangeLow: 256,
        rangeHigh: 383,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 9 }, { type: 'PC' }]
      },
      {
        rangeLow: 384,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 10 }, { type: 'PC' }]
      }
    ],
    'SRX-07': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 11 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        rangeHigh: 255,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 12 }, { type: 'PC' }]
      },
      {
        rangeLow: 256,
        rangeHigh: 383,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 13 }, { type: 'PC' }]
      },
      {
        rangeLow: 384,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 14 }, { type: 'PC' }]
      }
    ],
    'SRX-08': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 15 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        rangeHigh: 255,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 16 }, { type: 'PC' }]
      },
      {
        rangeLow: 256,
        rangeHigh: 383,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 17 }, { type: 'PC' }]
      },
      {
        rangeLow: 384,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 18 }, { type: 'PC' }]
      }
    ],
    'SRX-09': [
      {
        rangeHigh: 127,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 19 }, { type: 'PC' }]
      },
      {
        rangeLow: 128,
        rangeHigh: 255,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 20 }, { type: 'PC' }]
      },
      {
        rangeLow: 256,
        rangeHigh: 383,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 21 }, { type: 'PC' }]
      },
      {
        rangeLow: 384,
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 22 }, { type: 'PC' }]
      }
    ],
    'SRX-10': [
      {
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 23 }, { type: 'PC' }]
      }
    ],
    'SRX-11': [
      {
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 24 }, { type: 'PC' }]
      }
    ],
    'SRX-12': [
      {
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 26 }, { type: 'PC' }]
      }
    ],
    'SRX-97': [
      {
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 97 }, { type: 'PC' }]
      }
    ],
    'SRX-98': [
      {
        commands: [{ type: 'CC', number: 0, value: 93 }, { type: 'CC', number: 32, value: 98 }, { type: 'PC' }]
      }
    ]
  }
};
