import { ExpansionCard } from '../../../types';

export const srJV80_08: ExpansionCard = {
  name: "Keyboards of the '60s and '70s",
  number: 'SR-JV80-08',
  patches: [
    'Blues Perc',
    'A LittleHelp',
    'Big Pink B',
    'Hush B3',
    'Sly Family B',
    '3 Dog B3',
    'SanFrancisco',
    'Full Stops',
    'Head Up B3',
    'Full Clique',
    'So Very BS&T',
    'R&R B3 1',
    'Organ Banks',
    'Express Way',
    '85 8808 880',
    'R&R B3 2',
    'MelloDrama',
    'B3 Sermon',
    'British B3',
    'All Skate!',
    'Br.Ballad B3',
    'Pure Bars',
    'R&B B3',
    'Felix Ballad',
    'Fudge Ballad',
    'B3 Nice Feel',
    '85 5000 050',
    'Theatrix',
    'Barleycorn',
    'Majic Carpet',
    'All Star B3',
    "BT & MG's B3",
    "Bookin' B",
    'Rock Steady',
    'NICE L100',
    'Tenderness',
    'Blue B',
    'HeavyTraffic',
    'Dyno Rotary',
    'Concert B3',
    'Salty Dog',
    "Stevie's B3",
    'Hang Twice',
    'Let It B',
    'LA Blues',
    'Mellow Blues',
    'PentaGospel',
    'Sweet&Mellow',
    '2B orNot2B3?',
    'Green Bee',
    'Whiter Shade',
    'Fire Perc',
    'Sunset Strip',
    'B3 JazzSplit',
    'Evil Ways',
    'Dyno Perc B3',
    '888+3rd',
    '8888+3rd',
    'House Organ',
    'Easy to B',
    'Harum Scarem',
    'Green Eyed',
    '8888+3rd Vel',
    'Shine On B3',
    'Procol Perc',
    'Full Perc',
    "Mellow 4'",
    'ZomBee 3',
    'Hi Harmonix',
    'Rotary Banks',
    'Gimme Some',
    'Fuzzhead',
    'Traffiking',
    'B3powerOnOff',
    'ToneWheelPno',
    'Orgiano',
    'TVA FX ORG',
    'Animalistic',
    'Animal Mod',
    'Rising Sun',
    'Surf Monkeys',
    'Palisades',
    'Soul Kitchen',
    'BreakOnThru',
    'Calif.Sun',
    "Steppin' VX",
    'Costello+Mod',
    'VX Rotary',
    "Archie's Mod",
    'Telstar VX',
    'Cheeseball',
    'The Sham',
    'Cheese Pad',
    'Crummy Organ',
    'VX Religion',
    'Farfi Combo',
    'RotaryCheese',
    'Iron Farf',
    'DancingQueen',
    "PoorMan's B",
    'Reggae Organ',
    'Farf Lite',
    'Wooly Farfy',
    'Clark Farf',
    'Pacemaker',
    'Farf Celeste',
    'Ham & Cheese',
    'Rox Organ P',
    'Rox Organ Ph',
    'Rox Organ PH',
    'Rox Organ L',
    'Runaway',
    'Ditty Doo',
    'VX Wah Org',
    'Suitcase 88',
    'Rhodes mkV',
    'ChorusRhodes',
    'NY Rhodes',
    'Touch Rhodes',
    'Stage 73',
    "Joe's Rhodes",
    'Stiff Rhodes',
    'Dirty Rhodes',
    'Mr.Suitcase',
    'Jazz Rhodes',
    'HybridRhodes',
    'Dyno Rhodes1',
    'Dyno Rhodes2',
    'Dyno Rhodes3',
    'Ring Rhodes',
    'LoungeRhodes',
    'TremSuitcase',
    'Preacher',
    'Hard Rhodes',
    'BalladRhodes',
    'Wide Rhodes',
    'Soft Fusion',
    'Phase Rhodes',
    'SpaceyRhodes',
    "I'mNotinLove",
    'Vinyl Rhodes',
    'Bread Rhodes',
    'Mutro Rhodes',
    "Ray's Pno Bs",
    'SynRhodes Bs',
    'Soft Wurly',
    "What'd I say",
    'Dry Wurly',
    'Chorus Wurly',
    'Acid Wurly',
    'Hard Wurly',
    'Tramp Wurly',
    'Tremo Wurly',
    'Smooth Wurly',
    'Grungy Wurly',
    "Breakin' Up",
    'Dist Wurly 1',
    'Dist Wurly 2',
    'Dist Wirly 3',
    'Dist Wurly 4',
    'Whirling',
    'RingMod Solo',
    'Rider/Storm',
    'Pnet Tee',
    'Stereo Pnet',
    'ShesNotThere',
    'R&B Pnet',
    'BrillantPnet',
    'Rox+Pnet',
    'Rox Piano 1',
    'Rox Vinyl',
    'Rox Piano 2',
    'Crummy Piano',
    'Rox Lute',
    'Rox Lute Ch.',
    'Rox Full+Acc',
    'Rox Pi/Ha',
    'Carpet Crawl',
    'Rox Jacuzzi',
    'TrickOfTail',
    'Rho/Wurl/Rox',
    'Rox Chorus',
    'Rox Harpsi',
    'Farfi Harpsi',
    'Octa Harpsi',
    'VX Harpsi',
    'PowerFlowers',
    'Rox Grinder',
    'Clav 1',
    'Clav 2',
    'Clav 3',
    'Clav 4',
    'Clav 5',
    'Clav 6',
    'Clav 7',
    'Phase Clav 1',
    'Rich Clav',
    'Vibraclav',
    'Mute Clav 1',
    'Mute Clav 2',
    'Flange Clav',
    'Comp Clav',
    'Space Clav',
    'Mute Clav 3',
    'Bass Clav',
    'Phase Clav 2',
    'Brite Clav',
    'WahWah Clav1',
    'WahWah Clav2',
    'Clv/Pnet Sp',
    'Clv/PnetDuo1',
    'Clv/PnetDuo2',
    'TronStrg ENS',
    'Tron Str Dry',
    'Rotary Tron1',
    'Rotary Tron2',
    'St.Tron Dry',
    'TronOctStack',
    'SmoothTron1',
    'SmoothTron2',
    'Slow Tron',
    'SymphonicTrn',
    'Moody Tron',
    'Warm Tape',
    'Tron Vls Dry',
    'Mello Vlns',
    'Tron Cello',
    'Mello Cello',
    'Tron Quartet',
    'Tron Orch',
    'DryStr/Choir',
    'Tron Vox',
    'Wet & Wiggly',
    'TronChoirDry',
    'Tron Choir',
    'Old Choir',
    'FatTronChoir',
    'Choir Blend',
    'Slow Choir',
    'Retroactive',
    'LamenTron',
    'Anthem',
    'Space Tron',
    'MelloMemries',
    '5th Tron Str',
    'Tron Vortex',
    'PlanetClaire',
    'Rox Strings',
    'Harpsiphase',
    'Cheep Phazer',
    'Swimming Bee',
    'Old Lead',
    'Organ Lead',
    'Techno Cheese',
    '33 RPM'
  ]
};
