import { ExpansionCard } from '../../../types';

export const srJV80_04: ExpansionCard = {
  name: 'Vintage Synth',
  number: 'SR-JV80-04',
  patches: [
    'Prologue',
    'EasternTempl',
    'Replicants',
    'Converge',
    'JX3P Polaris',
    'Big Pad Swp',
    'Big LFOSweep',
    'Animotion',
    'Mega 5ths',
    'CS-Sixty BPF',
    'Waspy Synth',
    'Polychrome',
    'Euro Sweep',
    'OBig Poly',
    'OB Synthy',
    '80s OBxa',
    'Thick Matrix',
    'Poly X-pandr',
    'Synth-X Poly',
    'Prophetic',
    'Oct MG Saw',
    'Juno 6 Power',
    'Hyperphases',
    'Synth-X Phaz',
    'MIDI Brs Pad',
    'Poly Palette',
    'Spit Brass',
    'Pro-10 Brass',
    'OB Stab Brs',
    'Pro-5 Brass',
    'MKS-7 Brass',
    'Quack Brass',
    'MemoryMG Brs',
    'FM Brass',
    'Ghost Blow',
    'Metal Drone',
    'Rotary Strng',
    'Random Pad',
    'S/H Texture',
    'Warm Shimmer',
    'Nervous Pan',
    'JX-3P Planet',
    'JX Melon Vox',
    'Horror Pad',
    'Shining Wave',
    'The Big Wave',
    'Mantrawave',
    'WavetablePan',
    '2.3 GlassSEQ',
    'VS Organbell',
    'DigitalChoir',
    'Additive',
    'Tower Silvis',
    '2.2 Rezidue',
    'Polysync',
    'Wavesync',
    'Rock Sync',
    'Kalimbasynth',
    'Stacc Heaven',
    'D50 Bellpad 1',
    'D50 Bellpad 2',
    'D50 Bellpad 3',
    'Snow Lake',
    'Time flies',
    'Fanta - Retro',
    'SimpleEP+Pad',
    'Juno-1 Bells',
    'Random Chime',
    'Asia Wave',
    'GoodniteBell',
    '2600 TRIbell',
    'Twinkle',
    'Analog Chime',
    'Space Echo',
    'Ethno Stack',
    'SH-1000 MIDI',
    'ElectraPiano',
    'Rhodes Pad',
    'Sine Piano',
    'VCO Wurly',
    'Clavipad',
    'P10 GuitClav',
    'Gum Clav',
    'JunoBiteClav',
    'Phazyn Clav',
    'JP-8 Clav',
    'Alpha Clav',
    'Hyper Clav',
    'Perky Pad',
    'Perkolator',
    'MondoDiGiTaL',
    'Poly Flange',
    'and thenMIDI',
    'JP4Sharp Pad',
    'Splatty',
    'MKS80 Sprang',
    'JP8 Stringsl',
    'JP8 Strings2',
    'JP+OB Strngs',
    'Wavestrings',
    'PWM Strings',
    'MemoryMG STR',
    'OB Thick Pad',
    'OB Soft Pad',
    'OctavaStrngs',
    'CS Saw Pad',
    'CS Strings',
    'Solina',
    'Rhapsody STR',
    'Big Strings',
    'Juno 106 Pad',
    'Majesty Pad ',
    'Peaceful Pad',
    'Flange strng',
    'JP SquarePad',
    'HollowBreath',
    'Hollow JX',
    'DarkEnsemble',
    'LonesomeHill',
    'VP-330 Choir',
    'VP-330 Tutti',
    'VP-330 Sweep',
    'RS-202 Brass',
    'Orchestrator',
    'OBJX Vox Pad',
    'Voices JX-8P',
    'D50 Heavenly',
    'Mini Lead 1'
  ]
};
