import { ExpansionCard } from '../../../types';

export const srJV80_07: ExpansionCard = {
  name: 'Super Sound Set',
  number: 'SR-JV80-07',
  patches: [
    'Ac.Piano 1',
    'Ac.Piano 2',
    'Soft Piano',
    'U-220 APiano',
    'FortePiano',
    'Honky Tonk',
    'Pop Piano',
    'Dusty Piano',
    'NewAge Piano',
    'E.Grand 1',
    'E.Grand 2',
    'E.Grand mod',
    'U-220 EGrand',
    'Stage EGrand',
    'E.Grand ff',
    'E.Piano mod',
    'Soft Rhodes',
    'St.Rhodes',
    'Tremelo EP',
    'Long is...',
    '...the Road',
    'High Rhodes',
    'Bright EP 1',
    'Bright EP 2',
    'Bright EP 3',
    'Bright EP 4',
    'Syn.E.Piano',
    'Xmod E.Piano',
    '<D>gtalPiano',
    'Hps Front 1',
    'Hps Front 2',
    'Hps Front 3',
    'Hps Back 1',
    'Hps Back 2',
    'Hps Back 3',
    'Hps Back 1T',
    'Hps F/B',
    'Hps F4/B',
    'Hps F/B/B4',
    'Hps Lute 1',
    'Hps Lute 2',
    'Hps Lute 3',
    'Hps Lute 1T',
    'Medieval Ens',
    'Baroque Ens.',
    "'60 CompKlav",
    'House Clav.',
    'Phase Clav.',
    'Org Flutes 1',
    'Org Flutes 2',
    'Org Flutes 3',
    "Org Flute 8'",
    'Church Organ',
    'English Org',
    'Organ Chord',
    'Happy Xmas !',
    '1001 Nights',
    'G.Star 1',
    'G.Star 2',
    'Dream Time',
    'Clavi Pad',
    'into Dream',
    'Not Old',
    'Box Guitar 1',
    'Box Guitar 2',
    'Reso Guitar',
    'V-MX Guitar',
    'Flat Picker',
    'Steel Guitar',
    'Steel there!',
    'BriteJGuitar',
    'Tympanon',
    'Live Guitar',
    'Arabic Scale',
    'Big Twelve',
    'Jazz Guitar',
    'St.Jazz Gtr',
    'Pedal Steel1',
    'Pedal Steel2',
    'Stereo Pedal',
    'Pedal Steel3',
    'Dyno Steel',
    'Super Steel',
    'Pedal Steel4',
    'PedalSteelSW',
    'Steel Fours',
    'Pedal Steel5',
    "Clean'd Comp",
    'Blues Guitar',
    '335 Guitar',
    'St.335 Pick',
    '335 VSW Pick',
    '335 Mute',
    '335 St. Mute',
    'Echo Mute',
    'VeloMute+Pik',
    'All Mutes',
    'Mute Guitar',
    'BriteChorus',
    'Clean Pick 1',
    'Clean Pick 2',
    'Clean E.Gtr',
    'Phase Guitar',
    'PickChordsX4',
    'Super Picker',
    'St. Pick',
    'Dist Guitar',
    'HEAVY !',
    'St.Dist Gtr',
    'Super Heavy',
    'Mandolin 1',
    'Mandolin 2',
    'Mandolin 3',
    'Mandolin 4',
    'Mandolins',
    'SuperMando',
    'ResonatorGt1',
    'ResonatorGt2',
    'ResonatorGt3',
    'Dobraccent',
    'Dulcimer 1',
    'Dulcimer 2',
    'Dulcimer 3',
    'Gamelan Ens.',
    'Guitar Pad',
    'Bass Mix',
    'Musette tun',
    'Musette det1',
    'Musette det2',
    'Master 1',
    'Master 2',
    'Jazz',
    'Bandoneon1',
    'Bandoneon2',
    'Bs/Musettun',
    'Bs/Musetdet1',
    'Bs/Musetdet2',
    'Bs/Master1',
    'Bs/Master2',
    'Bs/Jazz',
    'Bs/Bandoneon1',
    'Bs/bandoneon2',
    'Reed Organ1',
    'Reed Organ2',
    'Rive Gauche',
    'Iturbynth',
    'Bandeneon Duo',
    'Amsterdam',
    'Sad Musette',
    'Fiddle 1',
    'Fiddle 2',
    'Super Fiddle',
    'Fiddle About',
    'DigitalCello',
    'Four Seasons',
    'Staccato',
    'Tremelo 1 /',
    'Tremelo 2',
    'Tremelo 3 /',
    'Sop Rec  1T',
    'Tenor Rec 1T',
    'Rec Twin',
    'Rec Sect',
    'Recorder 1T',
    'Living Pipe',
    'Pipe Lead',
    'Whistle',
    "Fr'm Scotlnd",
    'Soft Sax',
    'Bright Sax',
    'St.Sax',
    'Bright TP',
    'Trombone',
    'Trombone SW',
    'Twinbone',
    'Super TB',
    'St.Trombone',
    'St.Soft TB',
    'St.Bright TB',
    'Fat Trombone',
    'Brass Sect 1',
    'Brass Sect 2',
    'Brass Sect 3',
    'Pizz Bass',
    'Sax Sect 1',
    'Sax Sect 2',
    'In the Mood',
    'Orchestra',
    'BrassOrchest',
    'Jazz Quartet',
    'B!G Stab',
    'Brass Fall 1',
    'Brass Fall 2',
    'Brass Fall 3',
    'Tp Fall 1',
    'Tp Fall 2',
    'Brass Stacc',
    'F.Horn Rip 1',
    'F.Horn Rip 2',
    'Mild ANALOG',
    'Black Ring',
    'Steel Brass',
    'S.JV Marine',
    'CarminaB/Aft',
    'Cosmic Vox',
    'Digital Vox',
    'Y Empire',
    'Cosmic Echo',
    'She does ...',
    'Sine Strings',
    'Chineez Wave',
    'Metalattack',
    'EG Vox',
    'Metal Sweep',
    'Digi Sweep',
    'Deep Space',
    'Blue Mist',
    'Trailer Pipe',
    'Cluster',
    'Pentatonic',
    'RoaringSpace',
    'Deep Cave',
    'Kokoro',
    'Nothing Air',
    "Mick'm House",
    'Mello Orch.',
    'Saturn',
    'Orch Hit Maj',
    'Orch Hit Min',
    'Orch Hit Dim',
    'Big Hits Maj',
    'Fanfare   /',
    'Owz it !',
    'Rave OrcHit',
    'OrchHit X',
    'OrchGlissMaj',
    'OrchGlissMin',
    'Orch End FX',
    'Harp m7',
    'Harp 9th',
    'Harp +7',
    'Harp b9',
    'Harp m7 Scrl',
    'Harp 9thScrl',
    'Harp +7 Scrl',
    'Harp b9 Scrl',
    'Groove 1',
    'Drum Set 1',
    'Drum Set 2',
    'Drum Set 3',
    'Drum Set 4',
    'Drum Set 5',
    'Drum Set 6',
    'Drum Set 7',
    'CountryDrums'
  ]
};
