import { ExpansionCard } from '../../../types';

export const srJV80_02: ExpansionCard = {
  name: 'Orchestral',
  number: 'SR-JV80-02',
  patches: [
    'Warm Violins',
    'Slow Vlns 1',
    'Vlns+Vlas 1',
    'Vl Sect mono',
    'Arco Violins',
    'Marcato Vls1',
    'Vlns+Vlas 2',
    'Agitato Vls1',
    'Rosin Pad 1',
    'Dry Mid - High',
    'Natural Vlns',
    'Sad Vln Sect',
    'Marcato Vas',
    'Arco Violas',
    'Thick Violas',
    'Va Sect f',
    'Va Small Sec',
    'Agitato Vas1',
    'Sad Violas',
    'Fast Cellos1',
    'Vcs Legato 1',
    'Marcato Vcs1',
    'Small Vc Sec',
    'Agitato Vcs1',
    'Small Cellos',
    'Sad CelloSec',
    'Cb Sect ff',
    'Wide Basses',
    'mf Basses',
    'Agitato Cbs1',
    'Vcs+Cbs',
    '2 Basses',
    'Euro Strings',
    'Rich Strings',
    'Multi Strs 1',
    'VlsVasVcsCbs',
    'Bright Strs',
    'Classicl Str',
    'Full Strings',
    'Med Str Sec',
    'Small Strngs',
    'Strings Arco',
    'Vivace Strs',
    'Agitato STR1',
    'LowSTR Attak',
    'Bad Guy STR',
    'Ominous',
    'Lo Express',
    'DramaStrings',
    'Solo Vln 1',
    'Solo Vln 2',
    'Chorus Vln',
    'Stereo Vln',
    'Agitato Vln1',
    'Solo Vla 1',
    'Solo Vla 2',
    'Chorus Viola',
    'Stereo Viola',
    'Agitato Vla',
    'Solo Vc 1',
    'Solo Vc 2',
    'Stereo Cello',
    'Chorus Cello',
    'Marcato Vc 1',
    'Solo Cb 1',
    'Solo Cb 2',
    'Marcato Cb 1',
    'Chamber Ens1',
    'Chamber Ens2',
    'Vln+Vla Dble',
    'Vln+Vc Dbl1',
    'Vla+Vc Dbl2',
    'Vla+Vc Dble',
    'Pizzicato 1',
    'Mono Pizz',
    'Pizzicato 2',
    'Room Pizz',
    'Hall Pizz',
    'Tight Pizz',
    'Short Pizz',
    'STR Marcato1',
    'Oct Marcato',
    'Lower Marc!!',
    'Big Marc!',
    'STR Spiccato',
    'Fast Attacks',
    'Flute',
    'Flute V - Sw',
    'Piccolo',
    'Piccolo Flt',
    'Recorder',
    'Oboe 1',
    'Oboe 2',
    'Oboe 3',
    'Oboe 4',
    'Oboe 5',
    'English Hrn1',
    'English Hrn2',
    'English Hrn3',
    'Bassoon 1',
    'Bassoon 2',
    'Clarinet 1',
    'Clarinet 2',
    'Bs Clarinet1',
    'Bs Clarinet2',
    'Trumpet 1',
    'Trumpet 2',
    'Trumpet 3',
    'Flugelhorn 1',
    'Flugelhorn 2',
    'Cornet 1',
    'Cornet 2',
    'Solo Tb 1',
    'Solo Tb 2',
    'Solo Tb 3',
    'Solo Tb 4',
    'Bs Tb 1',
    'Bs Tb 2',
    'Harmon Mute1',
    'Harmon Mute2',
    'Tuba 1',
    'Tuba 2',
    'Solo F.Horn1',
    'Solo F.Horn2',
    'Sml F.Hrn sc',
    'Horn Sect 1',
    'F.Horn sc x4',
    'Fr.Horn sfz',
    'F.Hrn Sect2',
    'F.Hrn Sect3',
    'F.Hrn Sect4',
    'F.Hrn Sect5',
    'F.Hrn Sect6',
    'F.Hrn Sect7',
    'F.Hrn Sect8',
    'MuteHrn Sect',
    'Horn+Wood 1',
    'Horn+Wood 2',
    'Horn+Wood 3',
    'Wood Sect 1',
    'Wood Sect 2',
    'Wood Sect 3',
    'Wood Sect 4',
    '2 Oboes',
    'Oboe + Cla',
    'Flt + Piccl',
    'Flute + Cla',
    'Bassoon+EHrn',
    'Hi Woodwinds',
    'WoodwindSplt',
    'Multi Reed',
    '4 Trombones',
    'Tb Sect 1',
    'Tb + Tp',
    '4 Trumpets',
    '3 Trumpets',
    'Brass ff 1',
    'Brass ff 2',
    'Brass ff 3',
    'McArthur Brs',
    'Big Bones',
    'BassBoneSect',
    'Brass Swell',
    'Full Brs 1',
    'Brass Sect1',
    'Brass Ens 1',
    'Brass Ens 2',
    'Brass Ens 3',
    'Brass Ens 4',
    'Brass Ens 5',
    'Brass Ens 6',
    'Brass Ens 7',
    'Brass Ens 8',
    'Horn Strings',
    'Full Orch.1',
    'Full Orch.2',
    'Full Orch.3',
    'Full Orch.4',
    'Maj Hit 1',
    'Min Hit 1',
    'Dim Hit 1',
    'Major Stab!',
    'Maj Hit 2',
    'Min Hit 2',
    'Classical Gt',
    'Harp 1',
    'Harp 2',
    'Plucked Harp',
    'Harp StrumMj',
    'Harp StrumMn',
    'Water Harp',
    'ClasclPiano1',
    'ClasclPiano2',
    'ClasclPiano3',
    'ClasclPiano4',
    'Harpsichord1',
    'Harpsichord2',
    'Harpsichord3',
    'Harpsichord4',
    'Celesta 1',
    'Celesta 2',
    'Celesta 3',
    'Glockenleste',
    'Marimba',
    'BassMarimba1',
    'BassMarimba2',
    'Vibe',
    'Xylophone 1',
    'Xylophone 2',
    'Xylophone 3',
    'Glocken 1',
    'Glocken 2',
    'ChurchBells1',
    'ChurchBells2',
    'ChurchBells3',
    'TubulaBells1',
    'TubulaBells2',
    'Big Tubulars',
    'Dawning',
    'MalletStack1',
    'MalletStack2',
    'MalletStack3',
    'MalletStack4',
    'Malletstack5',
    'MalletStack6',
    'MalletStack7',
    'Choir 1',
    'Choir 2',
    'Snare Drum',
    'ConcertSNR1',
    'ConcertSNR2',
    'SNR Roll',
    'Concert BD1',
    'Concert BD2',
    'BD Roll',
    'Timpani 1',
    'Timpani 2',
    'Timpani 3',
    'Timpani 4',
    'Tam Tam',
    'Gong',
    'Piatti!!',
    'Sleigh Bells',
    'Slapstick',
    'Wind Chimes1',
    'Wind Chimes2',
    'Tambourine',
    'Castanets',
    'Rhythm Set',
    'Perc Hit 1',
    'Perc Hit 2',
    'Perc Hit 3',
    'Presenting!',
    'Presto!',
    'Christmas!!!'
  ]
};
