import { ExpansionCard } from '../../../types';

export const srJV80_16: ExpansionCard = {
  name: 'Orchestral II',
  number: 'SR-JV80-16',
  patches: [
    'StStrOrc p/f',
    'StrSwell/Mod',
    'Emotionale',
    'Dynamic Str',
    'Str DownBow',
    'Adagio Str',
    'Dyna Marc',
    'FourSeasons2',
    'StrOrch /Vel',
    'StrOrch p/f',
    'StatelyBrite',
    'RichSymphony',
    'St.StrOrch p',
    'St.StrOrch f',
    'RichStrings2',
    'FullStrings2',
    'MedStr Sect',
    'DynamicRosin',
    '101 Violins',
    'Natural Str',
    'Fast Strings',
    'Fat Marcato',
    'StrAtk 2',
    'DecayStrings',
    'Piano Str',
    'PyanniString',
    'Pno/Hrp Str',
    'Quartet',
    'Solo&Acomp',
    'Vln&Vcl',
    'Chamber Str ',
    'St.Cellos',
    'String Duet',
    'Vln&Vla Atk',
    'Stratovolo',
    'Vienna Solo',
    'AlternateBow ',
    'TronStrings2',
    'Tape Orchest',
    'Reverse Str',
    'SoloViolin 1',
    'SoloViolin 2',
    'Fiddle Spicc',
    'FdlGliss Vsw',
    'BariolageVln',
    'SadSolo Vln',
    'Chorus Vln 2',
    'Stereo Vln 2',
    'Agitato Vln2',
    'Solo Cello',
    'Dry Cello',
    'Solo Vc 3',
    'ChorusCello2',
    'Strngs&Horns',
    'FullOrchest2',
    'FilmOrchst p',
    'FilmOrchst m',
    'St.Orch Uni',
    'Horns/String',
    'Woody Orch',
    'Orch Ens',
    'Orch Unif',
    'Orch Brass 1',
    'Orch Brass 2',
    'GRAND Orch',
    'Last Noel',
    'Celtic Ensbl',
    'Harp & Flute',
    'Celesta&Flt',
    'Prokofiev',
    'Mass In Cee',
    'St.OrchBrass',
    'Dyn HornSect',
    'FrenchyHornz',
    'Simple Hornz',
    'Large Horns',
    'Fr.Horn p>f',
    'Fr.Horn sfz2',
    '2xFr.Horns',
    'Uni Hrns Duo',
    'Swell-brass',
    'Solo Fr.Hrn1',
    'Solo Fr.Hrn2',
    'Medieval OYA',
    'Orch Horns',
    'Brass Ens 9',
    'BrassAttack2',
    'Full Brass 1',
    'Full Brass 2',
    'Horn Accomp',
    'Mood Brass',
    'Trumpet Ens',
    '3 Trumpets2',
    'Centurions',
    'Real Trumpet',
    'Jazz Trumpet',
    'Trumpet 4',
    'Trumpet 5',
    'El Bono',
    'Solo Tb 5',
    'Solo Tb 6',
    'Solo Tb 7',
    'Trombone atm',
    'ConcertFlute',
    'Flute 2',
    'Flute 3',
    'Flute 4',
    'AmbientFlute',
    'Jig Flute',
    'Piccolo 2',
    'Piccolo 3',
    'PiccoloFlt 2',
    'Dyno Celt',
    'CelticFlt 1',
    'CelticFlt 2',
    'Celt Fl Trio',
    'TinWhistle 1',
    'TinWhistle 2',
    'TinWhistle 3',
    'Celtic Whisl',
    'Sinking Duo',
    'Beret',
    'Hill&Sheeps1',
    'Hill&Sheeps2',
    'HilandChurch',
    'C PentaPipe',
    'UilleanPipe',
    'Celt/Uillean',
    'Celt/Fiddle',
    'Oboe Vsw',
    'Oboe 6',
    'Oboe 7',
    'Clarinet 3',
    'English Hrn4',
    'English Hrn5',
    'Bassoon 3',
    'Bassoon 4',
    'Bassoon 5',
    'Oboe/E.Horn',
    'DelicateWood',
    'Oboe/Clari',
    'Jig Duo',
    'St.Bousouki',
    'Bousouki 1',
    'Bouski/Strum',
    'Bousouki 2',
    'Mafioso',
    "String'O Fun",
    'BosoukiDream',
    'St.Harp',
    'Harp Vsw',
    'Clear Harp',
    'African Harp',
    'Rich Harp',
    'Harp 3',
    'Harp Pf',
    'MelancolyHrp',
    'CelticHarp 1',
    'CelticHarp 2',
    'Clarsah Harp',
    'ElectraHarp',
    'ArpeggiHarp',
    'Harp Gliss',
    'St.Cymbalon',
    'Cymbalon',
    'Cymbalon Duo',
    'Bohemian',
    "Child's Toy",
    'Xmas Piano',
    'OnReflection',
    'Harmonium 1',
    'Harmonium 2',
    'St.Music Box',
    'Old Mechanic',
    'SecretGarden',
    'Music Box 2',
    'Victoriana',
    'Meditation',
    'TubulaBells3',
    'TubulaBells4',
    'TubulaBells5',
    'ChurchBells4',
    'BelfryChime2',
    'ChurchBells5',
    'HappyXmas! 2',
    'Sweet Dreams',
    'Huge Bells',
    'Glocken 3',
    'Mmms & Aaahs',
    'Pure Voices',
    'CelticSpirit',
    'Fem Ahs',
    'Perc DigiVox',
    'Fates',
    'Aah:VelScoop',
    "Heaven'sVox1",
    "Heaven'sVox2",
    'Mmh Vox 1',
    'Mmms',
    'Mmh Vox 2',
    'StChr Mm/Ah',
    'Umms & Aahs',
    'Humming Chrs',
    'Ether Choir',
    'ndtrkVoices',
    'WinterChoir2',
    'BreathVoices',
    'Fair...like!',
    'She Breathes',
    "Movin'Vowels",
    'Onya Vox',
    'Vox Ghost',
    'Spectral Mmh',
    'Soft Mover',
    'Analogue?',
    'Dark Knight',
    'Xreeds',
    'C.Harp/pad',
    'Phaze Strngs',
    'Phaze Choir',
    'Dreamsequenz',
    'Waterworld',
    'Midnight',
    'Colombus',
    'Titan',
    'Interspace',
    'Fountains',
    'SteppedGliss',
    'Your Mission',
    'Mondo Hit',
    'Orch Hit 1',
    'Big Hit',
    'Orch Hit 2',
    'Orch FX',
    'HorrorHit C4',
    'Dyna Timps',
    'Timpani 5',
    'Dark Drums',
    'St.Bodhran',
    'Bodhran Vel',
    'CrazyBodhran',
    'Bodhran Menu',
    'Percussn Mix',
    'Wind Chimes3',
    'Jingle Bell',
    'Finger Cym',
    'Cym Scrape',
    'TunedBlock 1',
    'TunedBlock 2',
    'TunedBlock 3',
    'Grongkas',
    'Orch Snare',
    'Snr Roll Vsw',
    'OrchSnr Menu',
    'Orch BassDrm',
    'OrchDrm Menu'
  ]
};
