import { ExpansionCard } from '../../../types';

export const srJV80_09: ExpansionCard = {
  name: 'Session',
  number: 'SR-JV80-09',
  patches: [
    'St.Concert',
    '9ft.Grand 1',
    '9ft.Grand 2',
    'Euro Classic',
    'St.Pno & Str',
    'Compress Pno',
    'LA Session',
    'Water Piano',
    'Vibra Rhodes',
    'Stack Rhodes',
    'ArcoEnsemble',
    'Vienna Strgs',
    'Str Adagio',
    'Oct Strings',
    'Silky Filter',
    'Soft Strings',
    'SlowStr.Sect',
    'GiantStrings',
    'Str+Choir 1',
    'Str+Choir 2',
    'Str+Choir 3',
    'Breathy Humz',
    'Dream Voices',
    'Mmmms',
    'Chorale',
    'Space Men',
    'Choir Mm+Aah',
    'Ivory Mist',
    'PercussiVox',
    'Mysteriouso',
    'Phase Mmhs',
    'AmbientStory',
    'Venus',
    'SessionBrass',
    'Port.Tpts',
    'R&R Brass',
    'Echo Brass',
    'E.Coast Brs',
    'Bop Soli',
    'Soft Saxes',
    'Orchestral',
    'Octalog Hrn',
    'Tpt Soloist',
    'Legato Tpt',
    'Dyno Trumpet',
    'Ethno-Trumps',
    'Super Tenor',
    'TenorExpress',
    'T.Sax f',
    'Legato Flute',
    'Touch Flute',
    'NewAge Flute',
    'Flute inMist',
    'Hybrid Flute',
    'Flute & Cla',
    'ChristmasFlt',
    'Fifth Flute',
    'Cosmic Flute',
    'Acc.de Paris',
    "Paris 50's",
    'Musette Ens',
    'Montmartre',
    'Sad Akordion',
    'Fr.Accordion',
    'Fr.Accord 2',
    'Troubadour',
    'SessionNylon',
    'Shaker MENU2',
    'Solo Nylon 2',
    'Nylon & Str',
    'Nylon & Flt',
    'Nylon Chord',
    'Stratar',
    'Clean Tele',
    'Nashville',
    'Super Trem',
    'SpaghettiGtr',
    "Duanne'sTone",
    'Big Hair Ld',
    'Metal Solo',
    'Crunch Tone',
    'Overdriven',
    'Blues Tele',
    'Tube Double',
    "Neil's Rust",
    'Short Crunch',
    'X-Fade Metal',
    'Velo Power',
    'Phazy Chunk',
    'Reso Tele',
    'Wah Wah BPM',
    'Rock P.Bass1',
    'Rock P.Bass2',
    'Rock P.Bass3',
    'Big Jazz Bs',
    'BriteJazz Bs',
    'Ch.Jazz Bs',
    'Mellow Jz Bs',
    '???',
    'Octabahn Bs',
    'Slobbery Bs',
    'Phase Worm',
    'Euro Rave Bs',
    "Pumpin' Bs",
    'Tech NoBase',
    'Bad Acid Bs',
    'CheepEcho Bs',
    'Manic Bs',
    'JP6 Sqr Key',
    'Square drops',
    'Celestial',
    'Heavenly Eko',
    'JD-800 Nomad',
    'Vibrolater',
    'MartianChime',
    'Big Wet Blip',
    'Amazing Echo',
    'DelaySession',
    'Deletex',
    'Tarlia',
    'Mahoroba',
    'Eurotek Clav',
    'Dope Resoclv',
    'Tekno Juno',
    'Buzzzzzzzzzz',
    'Slop-a-rama',
    "Isn't Pretty",
    'Polywasp',
    'Quixelate',
    'Trangoa Wave',
    'Spiked Cheez',
    'Glassy Cheez',
    'Super 808Cow',
    'Arpeggiatoid',
    'Euro Hit 1',
    'Euro Hit 2',
    'Rave Slice',
    'Str Torture',
    'Juno Harpsi',
    'Big Mess Pad',
    'Harpsichoir',
    'Echo Juno',
    'Phazerave',
    'DanceStack 1',
    'DanceStack 2',
    'DanceStack 3',
    'DanceStack 4',
    'DanceStack 5',
    'DanceStack 6',
    'DanceStack 7',
    'DanceStack 8',
    'Eurotek Brs',
    'Synergy Brs',
    'PortaSynthex',
    'Razor VCOs',
    'Big PWM',
    'Flutey Stack',
    'Wobbly 5th',
    'Tekno Square',
    'Trance VoXxX',
    'Random Rave',
    'Raver Circus',
    'Resorave',
    'Flangomatic',
    'O-Zu-Nu',
    'Sub Divided',
    'Ancient Sqr',
    'Fat Flange',
    'Phaze NRG',
    'Phase Vox',
    'Systekno',
    'On the move!',
    "XP'ration",
    'Big Ensemble',
    'Lazerette',
    'Fazed String',
    'Combing Slow',
    'Jet Stack',
    'Phazeslopad',
    'Rize Mass',
    'Portent',
    'DCO Sweeper',
    'Sweep Rain',
    'Sweep Stack',
    'Big Vectors',
    'Poly Swell',
    'Alchemy',
    'Soli-na',
    '90s Str Mach',
    'Ultra Cheez',
    'Juno-60  Pad',
    'Progressive',
    'Build-Up Syn',
    'Atlantis 2',
    'Perelandra',
    'Plutonium',
    'Nautilus',
    'Metal Dreams',
    'Glass Clouds',
    'Harmonicloud',
    'Shining Veil',
    'Ethereal JX',
    'Striking 5th',
    'Meow 5ths',
    'Stepflanger',
    'Happy LFOs',
    'Aero Insect',
    'Beat Sweeper',
    'Wormy Lead',
    'Atmo Lead',
    'Caliolead',
    'Tweedles',
    'Raw PWM',
    'Voc Solo 5th',
    'Dirty Lead',
    'Boostweeper1',
    'Boostweeper2',
    'B3 Filth',
    'Phazed Organ',
    'VSw Vibrafon',
    'SA Vibe',
    'Rich Vibes',
    'SpaceGamelan',
    'Toy Vibe',
    'Analog Bomb',
    'Seashore 2',
    'Creation',
    'Cyberjunkie',
    'Sci-Fi Bells',
    'Shine on',
    'DEMO Piano1',
    'DEMO Piano2',
    'DEMO PnoVox',
    'DEMO Str 1',
    'DEMO Str 2',
    'DEMO Str 3',
    'DEMO SynPuls',
    'DEMO 5thPad',
    'DEMO Choir',
    'DEMO Brass',
    'DEMO Tenor',
    'DEMO Tpt',
    'DEMO Flute',
    'DEMO Nylon',
    'DEMO PhaseGt',
    'DEMO DistGt1',
    'DEMO DistGt2',
    'DEMO Strat',
    'DEMO SlapBs',
    'DEMO P.Bass',
    'DEMO SynBs',
    'DEMO SynLead',
    'DEMO Insect',
    'DEMO Buzzzzz',
    'DEMO Crowd'
  ]
};
