import { ExpansionCard } from '../../../types';

export const srJV80_06: ExpansionCard = {
  name: 'Dance',
  number: 'SR-JV80-06',
  patches: [
    'All night!',
    'Tune Up',
    'Acidic Grv',
    "Techno'Hood",
    'Space Groove',
    'Odd FXM Loop',
    'Ultrarave',
    'Easy R&B  83',
    'Caveman   83',
    'SoulShake 83',
    'HipHop Jz 88',
    'Homeboy   88',
    'Gangsta 1 94',
    'Gangsta 2 94',
    "Nite'Hood 94",
    'Party Jam 94',
    'S2S 909   94',
    'Ragga     94',
    'DeepGrine 94',
    'lopendsw 100',
    'Danger   100',
    'Breakdwn 100',
    "Owl'Hood 100",
    'Lo-Fi    100',
    'Soulmate 106',
    'Swingtmb 106',
    'Squeaky  110',
    "Swingin' 110",
    "Shufflin'110",
    'Suprise1 116',
    'Suprise2 116',
    'Perc Jam 116',
    '909Dsco1 120',
    '909Dsco2 120',
    '909Dsco3 120',
    'Superfly 120',
    'DiscoCga 120',
    'Caravan  120',
    'Jungle 1 124',
    '808CowBl 124',
    'Jungle 2 124',
    "Cruisin' 124",
    '909Swing 124',
    'Human Bt 124',
    'Mover    124',
    'Jazzy    130',
    '909 Pump 130',
    "Jammin'  130",
    'HipHouse 130',
    'Fancy Sw 130',
    'HipNoKik 130',
    'FastEuro 136',
    'Justice1 136',
    'Justice2 136',
    'New Jack 136',
    'Latin Bt 141',
    'Darknian 154',
    'Beat Menu 1',
    'Beat Menu 2',
    'Beat Menu 3',
    'Beat Menu 4',
    'Dance Split',
    'Dance Piano',
    'Odd Piano',
    'House Piano',
    'Bright Piano',
    'Velo Piano',
    'Simple Piano',
    'Night Moods',
    "50's Organ",
    'Organ Tong',
    'Organic',
    'Old Organ',
    'Mod Amb.Pipe',
    'Notre Dame',
    'Legato Synth',
    'Summer Time',
    'Def Lead',
    'Minor Rave',
    'Major Rave',
    'Dance Lead',
    'Sync Lead',
    'HyperHiPass',
    'Mono Raver',
    'Mod-Trance 1',
    'Mod-Trance 2',
    'Rave at home',
    'ResoLoot',
    'Square Tone',
    'Trianglular',
    'JP Sub-Synth',
    'Saxy Jam',
    'Reso Pad',
    'Fat Stack',
    'ResoSequence',
    'Common Synth',
    'NewAnalogEra',
    'Monstrousnes',
    'Sharpy',
    'Dance Arp',
    'Oddigeree',
    'Monstrousity',
    'Arpeggio',
    'Dance Seq',
    'Fiesta',
    'Trance Stab',
    'Digistack',
    "RaviD'Choir",
    'Random Hits',
    'Fizzy',
    'Eurostab',
    'Triumph Stab',
    'Street Stab',
    'Kik x4',
    'Reverse Nz',
    '909 Tom',
    'HiHat Menu',
    'Rev Cymbal',
    'Bang x2',
    'Ragga Hit',
    'Fly Chord',
    "Ravin'Chor s",
    'Powertechit',
    'Organ Hits',
    'Choralvibe',
    'Trancey',
    'Sharp Hit',
    'Mc Hit x3',
    'Kutt Hit',
    'Galaxy Hit',
    'Reggae Chord',
    'Saw Horn x2',
    'Rave Hit',
    'Vinyl Opera',
    "Movin'Hit",
    '2Tone Hit',
    'Club Hit x4',
    "Big Ol'Stab",
    'Loopbits x2',
    'Slide Fx x2',
    'Spooky',
    'Section Hit',
    'Gtr Fx x4',
    'Breath Fx x4',
    'Sax Fx x3',
    'Tpt Fx x3',
    'Scratch x4',
    'Scratch Loop',
    'Stab Scratch',
    'Record Noize',
    'Fizzzz',
    'Hurray!',
    'Sci-Fi',
    'Whoo-Whoo!',
    'Zigzag',
    'Hip alarm',
    'ScratchMenu1',
    'ScratchMenu2',
    'ScratchMenu3',
    'Tape Spin',
    'Noise Menu',
    'PiknMixnMod',
    'Manic Shots',
    'Sonic Stabs',
    'Stylostab',
    'CutOffSnare',
    'Selecta Drum',
    'Trans Vox',
    'Aaaah!',
    'Ahoo Yell',
    'Oohh!!',
    'Madmam',
    'Oooh Yeah!',
    'Bah',
    'And!',
    'Aaa!',
    'Hey',
    'Baby',
    'Yeah-Yeah',
    'Oooooooooo',
    'Whoooooooo',
    'No-No',
    'OOO^^^^^^^',
    'Aaaa^^^^^^',
    'Laugh-Mix',
    'Vocamatic',
    'Girl Ah',
    'Vox Menu',
    'Rev Vox Menu',
    'Here We Go!',
    'Outhere Pad',
    'Tekno Voices',
    'Old Strings',
    'Dance String',
    'Terminator',
    'AmbientSweep',
    'Ambient BPF',
    "Oper'Ambient",
    'AmbientPad 1',
    'AmbientPad 2',
    'Lunar Orbit',
    'Fly-by Pad',
    'Sync Pad',
    'Urban Pid',
    'Deep Analog',
    'Garage Pad',
    'UK Slwing Pad',
    'Warriors',
    'Br.Jupiters',
    'M+C Big Pad',
    'Wonderous Pd',
    'Super OB',
    'Euro Srings',
    'Sweep Beat',
    'Nice-n-Easy',
    'World Muzic',
    'Tri-dent Brs',
    'Dance Brass',
    'Space Bass',
    'Clix Bass',
    'System 100m',
    'Synbass Five',
    'Rawsaw Bass',
    'Groove Bass',
    'Metalrezo Bs',
    'VCF Bass',
    'Sharp Rezo',
    'Technopop Bs',
    'Acid Tripper',
    'Hood Bass',
    'Housine Bs',
    'Anti-digital',
    'Dual VCF Bs',
    'Comic Bass',
    'TB-303 Bs 1',
    'TB-303 Bs 2',
    'SH-101 Bs 1',
    'SH-101 Bs 2',
    'SH-101 Bs 3',
    'SH-101 Bs 4',
    'SH-101 Bs 5',
    'How Odd?!',
    'Hell House',
    'Nightmare!!!',
    'Flangehead',
    'Doublefunky',
    'Mystical',
    'Sci-Fi Sweep',
    'Drum Set 1',
    'Drum Set 2',
    'Drum Set 3',
    'Drum Set 4',
    'Drum Set 5',
    'Drum Set 6',
    'Drum Set 7'
  ]
};
