import { ExpansionCard } from '../../../types';

export const srJV80_10: ExpansionCard = {
  name: 'BASS and DRUM',
  number: 'SR-JV80-10',
  patches: [
    'Marcus 3way',
    'MM Slap/Hrm',
    'MM Fat Slap',
    'Miller Pop',
    'MM Dynathumb',
    'Abe Sr. 4wat',
    'AL 3way/Nz',
    'AL 3way P Bs',
    'Abe Limiter',
    'Space Bass',
    'Hyper Funk',
    "Abe's Thumbs",
    'AL Dark Slap',
    "Poppin' Abe",
    'John P. w/Nz',
    'John P. w/Nz',
    'JP Chorus Bs',
    '6StringThing',
    'Mondo Johndo',
    'JP Flat Slap',
    'JP Brite Sla',
    'JP Fing+Slap',
    'Solo Fretles',
    'MM FretnotBs',
    'Marcus OctFl',
    'MM FrtlsBend',
    'MM Smooth Fl',
    'MM Weathery',
    "Abe's Fretls",
    'AL Fernch Ch',
    'AL Layer Fls',
    'AL Fls Solo',
    'JP 6Str Fls',
    'JP Solo Fls',
    "John's OctFl",
    'B-Motional',
    'Weather Frls',
    'AcoustiTouch',
    'JP Soft A.Bs',
    'JP Hard A.Bs',
    'Ac.Bs. Club',
    'Dry Acoustic',
    'Hybrid Wood',
    "John's Rock",
    'Pick Up',
    'JP Rock Pick',
    'Dark Pick',
    'JP Rock+Slap',
    'JP Rock Fls',
    'Velo Rock Bs',
    'JP P.Bass 1',
    'JP P.Bass 2',
    'JP P.Bass 3',
    'JP P.Bass 4',
    'Dyno Ballad',
    'Velo Fingers',
    'Ch. Fingers',
    'StudioMellow',
    'Fat Fingers',
    'Toucht Bass',
    "Abe's P.Bass",
    'AL Solid Fng',
    'AL 2way Fng',
    'AbeSoftBs/Nz',
    'Abe Latin Bs',
    'AL Latin Ch.',
    'AL Fat Latin',
    'AL Old Soul',
    'AL Mellow',
    'Marcus Jazz',
    'MM Jazz Ch.',
    'MM Jazz Bs',
    'Marcus Mute',
    'Bright Pick',
    'Garden Party',
    'Phaser Mute',
    'MM Dry Mute',
    'MM Hip-Hop',
    'Wild Thang',
    'Distorted Bs',
    'Rock Phaser',
    'Mod.Fuzz Bs',
    'Sticky Bass',
    'Abe Flangpop',
    'Mutey SynBs',
    "Funkin'WahBs",
    'T-Wow Fretls',
    'T-Wow Slappy',
    'Bass SOLO!!',
    'Refretter',
    'Bass Harmos',
    'Marcus Harms',
    'Harmonicus',
    'Tune Up',
    'Harm Up',
    'Harm Down',
    'Harm A#9',
    'Harm Eb#9',
    'Harm E+11',
    'Harm E69',
    'SlidesNoise',
    'All Slides',
    'All Noises',
    'Ac.Bs Noises',
    'Kick Menu',
    'Snare Menu 1',
    'Snare Menu 2',
    'Snare Menu 3',
    'Hi-Hat Menu',
    'Tom-Tom Menu',
    'Cymbals Menu',
    'Drum LP Demo',
    'Sweeping LPs',
    'Lo-Fi Loops',
    'AmbGrv/Bs 90',
    'SlapHappy 90',
    'PlayC4Fun 90',
    'Flanged 112',
    'BW Jz 6/8 52',
    'BW Brush 66',
    'AL Slam 66',
    'AL Whack 76',
    'AL Grunge 84',
    'BW Swamp 90',
    'BW Latin 102',
    'BW Fusion112',
    'AL Funk 120',
    'AL Shuff.126',
    'Fat Rock KIT',
    'Ringer KIT',
    'DynaPicc.KIT',
    'Whammer KIT',
    'BigBalladKIT',
    'Fat PunchKIT',
    'Fat Funk KIT',
    'Garage KIT',
    'Rock On KIT',
    'Natural KIT',
    'Pitched KIT',
    'Basher KIT',
    'Edgy KIT',
    'FAT Comp.KIT',
    'FAT & Tight',
    'Studio KIT',
    'Tight FunKIT',
    'TightPiccKIT',
    'Dry DanceKIT',
    'R&B KIT',
    'DynoSnareKIT',
    'Room Toms',
    'Natural Toms',
    'Soft Toms',
    'Big Toms Dry',
    'Big Toms Wet',
    'Ringer Snare',
    'Loud Ring Sn',
    'Live Piccolo',
    'Wet Piccolo',
    'Natural Crak',
    'Natural Verb',
    'Natural Bryt',
    'Dry Ringer',
    'Rock On Room',
    'Rock On Wet',
    'FAT Impact',
    'Nice Ballad',
    'Huge FAT Snr',
    'Warm Room Sn',
    'Warm Verb Sn',
    'Dry FAT Sn',
    'FAT Hall Sn',
    'Funk Sn Dry',
    'Funk Sn Room',
    'Natural Ping',
    'Room Ping',
    'Dance Snr 1',
    'Dance Snr 2',
    'Kick&Cym 1/2',
    'Kick&Cym 1/4',
    'Kick&Cym 2',
    'Butt Kicker',
    'Kick&Cym 2/3',
    'Kick&Cym 2/8',
    'Kick&Cym 3',
    'Kick&Cym 4',
    'Kick&Cym 5',
    'Kick&Cym 6',
    'Kick&Cym 7',
    'Kick&Cym 6/8',
    'Kick&Cym 8',
    'Kick&Cym 8/2',
    'Kick&Cym 9',
    'KickCym 9/6',
    'Kick&Cym 10',
    'Kick&Cym 11',
    'Kick&Cym 12',
    'Kik&Cym11/12',
    'Kick&Cym12/4',
    'Lo-Fi Kick',
    '18"Hi-Hats1',
    '18"Hi-Hats2',
    '16"Hi-Hats1',
    '16"Hi-Hats2',
    'CR-78 Hi-Hat'
  ]
};
