import { ExpansionCard } from '../../../types';

export const srJV80_05: ExpansionCard = {
  name: 'World',
  number: 'SR-JV80-05',
  patches: [
    'World Tour!',
    'Afropunch',
    'Yo How',
    'Kenya Split',
    'Intar Melody',
    'BerimbauMenu',
    'Thumb Chimes',
    'Velo Afro 1',
    'Bass Kalimba',
    'Buzz Kalimba',
    'Indalimba',
    'Thumb Piano',
    'Kalimba FX',
    'AfropercMenu',
    'Udu Pot Menu',
    'Udu Pots/',
    'Baateri',
    'Log Detuner',
    'Afroperk',
    'Glass Mallet',
    'Velo Afro 2',
    'Balafon /',
    'Hrd.Balafon',
    'Pure Balafon',
    'Big ole Logs',
    'Afro Log',
    'Angklungs',
    'BellAngklung',
    'Steel Drums1',
    'Steel Drums2',
    'War Drums',
    'AfricanMarch',
    'AfricanStomp',
    'Tribal Claps',
    'Kawala Str',
    'Space-o-rama',
    'Shakupad',
    'Ceremony',
    'Los Tremolos',
    'Lo Celloez',
    'Octargans',
    'Lo Ethnoreed',
    'Eastvox',
    'Black Rain',
    'Steel 5th',
    '5th Wind',
    '5th Bell',
    'Ocarawla',
    'Conch Call',
    'Sweep Floot',
    'Space Pipe',
    'PercssivRain',
    'Asian Chord',
    'Dell Ikhitt',
    'Ghost Metal',
    'Ring-RingPad',
    'Misterious',
    'Re - mind',
    'Whistle Vox',
    'Living Dead',
    'Earth Child',
    'Spaceilimba',
    'Drop of Rain',
    'Gaia Thought',
    'Es E.Piano',
    'Piri Rise',
    'Pandoras Box',
    'Ethno Dreams',
    'Snow Man',
    'Cuica Steps',
    'Saintly',
    'Trade Winds',
    'Pure Logic',
    'Earth Color',
    'Jawbreath',
    'AsiaCYM Menu',
    'Gong Menu',
    'Gong /',
    'China Menu',
    'Kabuki Menu',
    'Biwa',
    'Genderous',
    'Temple Metal',
    'Gomelan Tuti',
    'African Snow',
    'Bonang-Gam.',
    'Gamelan x4',
    'Saron-Gameln',
    'Temple Chime',
    'Prayer Bowls',
    'Hiten Bells',
    'Trash Metal',
    'Singing Bell',
    'Rama Chimes',
    'Rama Cymbals',
    'Tibet Bells',
    'Big Bowls',
    'Spoke Mallet',
    'Shakuhachi',
    'Shaku Accent',
    'Shakueko',
    'Pipe Melodi',
    'Flautwist',
    'Flute Press',
    'Zamponia',
    'Wosh Chiff',
    'Tramaloo',
    'FantasicPipe',
    'Pan Pipe /',
    'Random Zamp',
    'Zampona tr 2',
    'Ethno Pipesl',
    'Ethno Pipes2',
    'Ethno Pipes3',
    'Ocarina 3',
    'Quena',
    'Kawala',
    'Kawallabe',
    'Romance Exp',
    'Wind 7 Split',
    'Uni-Jig Pan',
    'OcarinaLead',
    'Zamp Lead',
    'Blown Touch',
    'Barkit',
    'Jungle Pipes',
    'C Shell+echo',
    'Atmospluck',
    'Afroharp Arq',
    'East/WestPlk',
    'Koto',
    'Zhueng',
    'Kotokeum',
    'Kayakeum Plk',
    'Asian Dawn',
    'Shamisen',
    'Noo Tye Whan',
    'Time Vault',
    'Afroharp 1',
    'OctHarp',
    'ChineseOrch2',
    'Euro Zither',
    'AfricaZither',
    'Zithgliss',
    'Hmr.Dulcimer',
    'Cymbalom',
    'Brt.Dulcimer',
    'Yangchin 1',
    'EasternTwang',
    '12th Knight',
    'Bandolim',
    'Cavaquinho',
    'Oud',
    'Mondo Oud!',
    'HybridStrung',
    'GlobalChorus',
    'Kanoum',
    'MultieastPix',
    'Yuehchin',
    'Crossbreed',
    'SoftRezituar',
    'Ethnic VLNx3',
    'Singil Piper',
    'Kulture Shok',
    'Erhu Lead',
    'ChineseOrch1',
    'Mosque Reeds',
    'E.Com Lead 1',
    'Piri Solo',
    'Mizmar',
    'Shahnai',
    'Hichirick',
    'VeloB',
    'Bagpipes',
    'Dholla Menu',
    'Egypt Tablah',
    'Madal Menu',
    'Dholak Menu',
    'TablaProcess',
    'Tinjaw',
    'Moroco FX',
    'Arabian',
    'TablanRhythm',
    'Tablafun',
    'Rattabla',
    'Sitarchestra',
    'Ravis Axe',
    'Passag2lndia',
    'Tambra Swirl',
    'Sitar ++',
    'Movie Synth',
    'Sitarsqeezer',
    'Sitar Gliss',
    'Tambura',
    'Tamb. Drone',
    'Breath Drum',
    'Tribe Switch',
    'Perc. Hit 1',
    'Perc. Hit 2',
    'Big Perc.Hit',
    'Doira Drum',
    'Bendir',
    'Chekere',
    'Rek Menu',
    'Shaker Menu',
    'Caixa Menu',
    'Cowbell Menu',
    'Bongo Set',
    'Guiro /',
    'Samba Menu',
    'Pandeiro Menu',
    'Surdo Menu',
    'Cuica',
    'Rain Stick',
    'Rotating Drm',
    'BellsOfSarna',
    'Comb.Loop 1',
    'Comb.Loop 2',
    'Comb.Loop 3',
    'Comb.Loop 4',
    'Comb.Loop 5',
    'Comb.Loop 6',
    'Slow.Loop 1',
    '2Bar Loop 1',
    '2Bar Loop 2',
    '2Bar Loop 3',
    'CylicSweep16',
    'Special Loop',
    'Samba Break/',
    'Bushroot',
    'Didgeridrone',
    'Dingodrone',
    'Didgeridoo',
    'Paila MG',
    'Ethno Bass 1',
    'Ethno Bass 2',
    'Farth Com Bs',
    'Clay HouseBs',
    'Berimbass',
    'Hunter',
    'Jawskin',
    'JawHarp Menu',
    'AfricaVoices',
    'Voice Set',
    'Zaghruta',
    'Maiting Call',
    'Lost my way.',
    'PlayLoHi F#m',
    'Going Deep',
    'Worm Hole',
    'Ethno Splash',
    'DinosaurPark',
    'BackwardGong',
    'AfricanQueen',
    'BedRock 5.30'
  ]
};
