import { ExpansionCard } from '../../../types';

export const srx05: ExpansionCard = {
  name: 'Supreme Dance',
  number: 'SRX-05',
  patches: [
    'SecretDancer',
    'Mean Streets',
    'E-tronic',
    'License2chil',
    'Scratch Menu',
    'Hit Specials',
    'Motivation',
    'Sine Vibrato',
    'Acid Punch',
    'E.Gtr Menu',
    'Brite Flange',
    'Dance Vibes',
    'N-Trance',
    'Phatt',
    'DoubleDown',
    'LoopFX Dark',
    'Yo DJ',
    'HH Piledrivr',
    'Trush Head',
    'Rap 21',
    'Teknobeat',
    'Filter Beat',
    'FashionStyle',
    'Strobobeat',
    'SpaceGroove2',
    'Underground',
    'Extra Drive',
    'NakedPrey',
    'Mod It!',
    "Broken'Roll",
    'Drew Groove',
    'Beat Menu',
    'Sinewave Bs',
    '808 Bass',
    'Low Bass 2',
    'Low Bass 3',
    'Low Bass 4',
    'Hood Bass 2',
    'Rubber Bs 21',
    'Cheezee Bass',
    'Bend Bs /sw',
    'Saws Bass',
    'Bass Kadett',
    'Qube Bass',
    'LegatoSynBs',
    '15inch Bass',
    'MG Filter Bs',
    'Plk Bass',
    'Flat SawBass',
    'SH-101 Bass',
    'Pulsing Bs',
    'Arrpy',
    'Acid Bass 2',
    'Euro Bass 21',
    'DarkEchoBass',
    'UnisonSwBass',
    'Dirty Bass',
    'Comp NzBass',
    'JunoDistBass',
    'TB Dist Bs 1',
    'TB Dist Bs 2',
    'TB Dist Bs 3',
    'Human Bass',
    'Interferenz',
    '16th SeqBass',
    'Woofer Blow',
    'Guitaron Oct',
    'Finger Bass6',
    'Noisy P.Bass',
    'FeelBass',
    'Ethno Bass 3',
    'FAT Rave',
    'JUNO Rave',
    '4 x Saws',
    'Euro Saws',
    'Super Sawz',
    'Step Phaser',
    'Vade Retro',
    'Pulse Keys',
    'P5 Pluck',
    'Alpha Waves',
    'Andes',
    'Northern Pls',
    'R&B Pluck 2',
    'SynHarpsi',
    'Saw Wave HQ',
    'Sqr Wave HQ',
    'JU2 Wave 1',
    'JU2 Wave 2',
    'Pulse Wave 1',
    'Pulse Wave 2',
    'SpectrumWave',
    'Pure Sine 2',
    'Slippers',
    'Climb Maj7th',
    'Return2Minor',
    'FallingStar',
    'Convulsions',
    'CrazZzeee',
    'Creative',
    'Juno Slice',
    'Epic Slice',
    'Klang Werk',
    'Ouverture',
    'Tropic Slice',
    'Strained',
    'Wicked DJ 2',
    'Ultra Noise',
    'JunoArpeggio',
    'Autoarpeggio',
    'SeqOctarveEP',
    'Sync Vox',
    'Stack Clavi',
    'Pump up',
    'Sine Seq',
    'Seq Saws',
    'Finale Hit',
    'Big Hit 3',
    'AnswerMe!Hit',
    'LoungeLizard',
    'Disco Stabs',
    "12x12'sDisco",
    'LittleDots',
    'TribalTechno',
    'Minor Bumwah',
    'Bobs Slide',
    'BrassHit 1',
    'BrassHit 2',
    'BrassHit 3',
    'BrassHit 4',
    'BrassHit 5',
    'BrassHit 6',
    'BrassHit 7',
    'SymphHit 1',
    'SymphHit 2',
    'SymphHit 3',
    'OrgTrnsplnt',
    'Organ Hit 3',
    'Organ Hit 4',
    'Chord Hit 1',
    'Chord Hit 2',
    'Chord Hit 3',
    'Chord Hit 4',
    'Crystal Hit',
    'Stamp Hit',
    'ThousandHit',
    '9th Hit',
    'Slap Hit 1',
    'Slap Hit 2',
    'Dust Hit',
    'Dist Hit 1',
    'Dist Hit 2',
    'Wah Hit',
    'Tremble Hit',
    'Dah Hit',
    'Pretty Hit',
    'Smoky Hit',
    'Fist Hit',
    'Clavy Hit',
    'Tread Hit',
    'Old Org Hit',
    'Cave Hit',
    'Thru Hit',
    'Mull Hit',
    'Electronica',
    'Ripper',
    'Bounce Hit1',
    'Bounce Hit2',
    'Hit OneShots',
    'Brass Stab',
    'Null Zone',
    'Loop Techno',
    'Tribal RaveX',
    'Raverlisious',
    '2FingerRifff',
    'UK Garage 01',
    'UKgarage2002',
    'XV-303',
    'Psy-Tron',
    'House128bpm',
    'NewAcid Line',
    'Raver Saws',
    'Dist Saws',
    'BoosterBips2',
    'Auto 101',
    'BPF Sweep',
    'Elektrico',
    'What The ??',
    'PlayEuroRiff',
    'MayhemAppegi',
    'AmbientTranz',
    'DanceStrSect',
    '5thIn4th Tri',
    '5th Vox',
    'Kompakt Voic',
    'Resound',
    'StrikeWhstle',
    'Rocket Blast',
    'Future Drain',
    'Foilage',
    'JP-8000 Pad',
    'SynthChord01',
    'PWM',
    'Introductory',
    'Miracle Pad',
    '5th Sweep 2',
    'Choir Sweep',
    'Retro Pad',
    'Beautiful:-]',
    'Steam Pad',
    'AggressiveLd',
    'I know Juno',
    'Def Lead 21',
    'HiPass',
    'DynaPulseLd',
    'Dist Lead',
    "80's Memory",
    'OD SyncLead',
    "80'sTechLead",
    '3-SquareLead',
    'PortaSynLead',
    'Tri Lead',
    'Corrupt Sine',
    'Neonlight',
    'Higher&Highr',
    'Waspy Solo1',
    'Waspy Solo2',
    'Vib Sine',
    'Legato Saw',
    'Wet Saw Ld',
    'Dry BassLead',
    'PluckLead',
    'Comp Piano 2',
    'a Tack Piano',
    'Analog Piano',
    'Tri Rhodes',
    'Pulsing EP',
    'Cool Rhodes',
    'Rhd Chd Menu',
    'Rhd Maj 9th',
    'Rhd Maj 11th',
    'Rhd Min 11th',
    'NoisySynthEP',
    'CompClav/Rls',
    'Comp Clavi',
    'HarmoOrg/Mod',
    'ZigZag Organ',
    'Notre Organ',
    'SpectrumBell',
    'Square Bell1',
    'Square Bell2',
    'ClnGtr Slide',
    'Gtr TrmDown',
    'Waw Chord',
    'Wha Wha Wha',
    'Wha De Da',
    'Fuzz Phaze',
    'Ringmod Ting',
    'BPF Strings',
    'LoFiStringz',
    'LightStrings',
    'Flange Str',
    '4th-LayerStr',
    'LA Pizz',
    'DanceClustor',
    'CaveStrHit',
    'StrChd Menu',
    'StrScaleMaj',
    'StrSpread',
    'EuroBeat Brs',
    'OB Brass 2',
    'Funny Brass',
    'Saws Brass',
    'AnalogMaster',
    'OneKeyMajor',
    'Danz Braz',
    'WindFX Menu',
    'Flute FX 1',
    'Flute FX 2',
    'Flute FX 3',
    'Sax FX 1',
    'Sax FX 2',
    'Sax FX 3',
    'VINYL VOX',
    'PsycheVocals',
    'Vox Menu',
    'Yeah F',
    'Ho F',
    'Oh F',
    'Wow Yeah F',
    'Ring Mod',
    'Hydrolyze',
    'Hydrolyze 2',
    'Danger Zone',
    'Danger Zone2',
    'Horror',
    'Space Scrach',
    'OldSkool FX',
    'Snare Bomb',
    'CymbalMusic',
    'Recollection',
    'Dive Start !',
    'DJ Mayhem',
    'TurnOff>Rev',
    'Scratch 4',
    'Scratch 5',
    'Scratch 6',
    'Scratch 7',
    'Scratch 8',
    'Scratch 9',
    'Scratch 10',
    'Vinyl Nz'
  ]
};
