import { ExpansionCard } from '../../../types';

export const srx01: ExpansionCard = {
  name: 'Dynamic Drums',
  number: 'SRX-01',
  patches: [
    'Kick 1 Menu',
    'Kick 2 Menu',
    'Kick 3 Menu',
    'Kick 4 Menu',
    'OldFnkS Menu',
    'Latin S Menu',
    'HiPiccS Menu',
    'Tight S Menu',
    'StdRk1S Menu',
    'StdRk2S Menu',
    'OhBabyS Menu',
    'PoppinS Menu',
    'StdFatS Menu',
    'JazStkS Menu',
    'StdJazS Menu',
    'BalladS Menu',
    'PwrBldS Menu',
    'AlBeefS Menu',
    'BigRckS Menu',
    '70BrshS Menu',
    'JzBrshS Menu',
    'CrsStk Menu',
    'Latin T Menu',
    'Tight T Menu',
    'JazStkT Menu',
    'OldFnkT Menu',
    'OhBabyT Menu',
    'PwrBldT Menu',
    'BigRckT Menu',
    'OldBrsT Menu',
    'OhBabyH Menu',
    'JazStkH Menu',
    'Latin H Menu',
    'Disco H Menu',
    'OldFnkH Menu',
    'StreetH Menu',
    'BigRckH Menu',
    'OldBrsH Menu',
    'Crash Menu',
    'Ride Menu',
    'OthrCym Menu'
  ]
};
