import { ExpansionCard } from '../../../types';

export const srx11: ExpansionCard = {
  name: 'Complete Piano',
  number: 'SRX-11',
  patches: [
    'Superb Grand',
    'WideStereoGd',
    'ClassicGrand',
    'Rock Grand',
    'Superior Grd',
    'PerfectGrand',
    'SingUsASong',
    'Dynamic Grd',
    'BriteOnStage',
    'BrightPopV/S',
    'Grand P1',
    'BrighterSide',
    'Full Rock pF',
    'Dark Ballad',
    'Grand P2',
    'Darker Side',
    'VelocaverPno',
    'Warm Room pF',
    'AntiqueUprit',
    'SuperiorMono',
    'Ragtime Gd',
    'Gnu House pF',
    'Archive Pno',
    "Lil' Takker",
    'Grand n Str',
    'Superior Str',
    'Sad Farewell',
    'Mixed Layer',
    'SuperiorPd1',
    'SuperiorPd2',
    'First Star',
    'New Age Layr',
    'Deep Breath',
    'Mc Reverse',
    'Meditate',
    'Penta Duo',
    'D-lightful',
    'Custom Clav',
    'Barococo',
    'Pianolins',
    'RandoMeistro',
    'Spooky Dimin'
  ]
};
