import { ExpansionCard } from '../../../types';

export const srx03: ExpansionCard = {
  name: 'Studio Expansion',
  number: 'SRX-03',
  patches: [
    'Y2K Plus One',
    'Pastoral',
    'Majestic',
    'Twin Strings',
    'Taxi Rhodes',
    'Peru Heights',
    'String Cloud',
    'Mysteria',
    'Mutes To Go',
    'HeavyMute/sw',
    'Wheel D-bar',
    "Kid's Glory",
    'GuitarInMist',
    'Overdrones',
    'RockAcoustic',
    'Piano Duel',
    'Chorus LA',
    "70's Blend",
    'OctopusPiano',
    'Rehoisal',
    'US Rhodes',
    'StudioRhodes',
    'All Rhodez',
    'Sens. Rhodes',
    'Harmonic Seq',
    'Still drumin',
    'B3 Mod/Aft',
    'B3 Perc',
    'DynOrgan',
    'Voxx Organ',
    'South Border',
    'Bright Nyle',
    "Rolin'Fingrs",
    'Nylon Vel',
    'Flamenco&Gtr',
    'Studio 12Str',
    'All AGuitars',
    'RichElec12st',
    'Electro-Ac.',
    'Jazzy /Slide',
    'Clean Comp',
    'Jazz Clean',
    'Jazz VelOct',
    '335 Amp+Chrs',
    'Switched On',
    'Tremolo Gtr',
    'NoThat Clean',
    'OhWow Guitar',
    'RED 5ths',
    'Touch Solo',
    "Fingr Tap'n",
    'Blues Grunge',
    '6-Str Bass',
    'Thumb&PullBs',
    '42nd Bass',
    'Mr. Jazz',
    'Picked JBass',
    'Upright Pizz',
    'Gt/BsNz MENU',
    'Lo Pizz Sect',
    'Octo Orch',
    'WindsFX MENU',
    'FluteVibrato',
    'Legato Flt 3',
    'Alto Flute',
    'Atk Flute',
    'SpaceFlute 2',
    'The Pan Pipe',
    'Breathy Pan',
    'Moceno',
    'Puffers',
    'Amazone',
    'Aztek ketzA',
    'Afro Flute',
    'SingingFlute',
    'GTR/Flt Scat',
    'Vox/Flt Scat',
    'Tape Flute',
    'Solo Trumpet',
    'Penny Tpt',
    'Mello TrBone',
    'DynamicBones',
    'Trumps&Bones',
    'Bigger Brass',
    'Brass Cooker',
    'Mod Sfz',
    'After Hours',
    "Mic'd Mute",
    'WarmBrsPad',
    'VCOs and As',
    'MG Brass',
    'Alto Sax Vel',
    'Honky Tenor',
    'Barely Bari',
    'Sax Sect mp',
    'Saxx-shun',
    'Psycho Sax',
    'HardSlidLead',
    'MonoLeads x2',
    'Tiny Love',
    "Soft Jup' LD",
    'MultiTap OB',
    'Night Blade',
    'Velo OB Str',
    'Meadow',
    'OB 5th Strng',
    'GhettoStrngz',
    'Octa Poly',
    'Pipewind',
    'Big & Gentle',
    'Ethernal',
    '3D MovingPad',
    'VintgStackSt',
    'St.ChldChoir',
    'HybrdChoirVS',
    'Swirly Mist',
    'St M+F Choir',
    'Cool Choir',
    'Mutatovox',
    'Dance Doos',
    'Dance OB',
    'Sliced Bread',
    'On&On&On',
    'Temptation',
    'Old Cartoon',
    'Swingtime',
    'Solar Winds',
    'Western'
  ]
};
