import { ExpansionCard } from '../../../types';

export const srx98: ExpansionCard = {
  name: 'Analog Essentials',
  number: 'SRX-98',
  patches: [
    'RealAnaSaw',
    'FullAnaSaw',
    'Forever',
    'StringsEns',
    'DryMG Lead',
    'EPw/GtrAMP',
    'TrancySaw1',
    'Distorted',
    'Sweep Saw',
    'MG Bass 1',
    'Dist Saw',
    'C-Piano',
    'Retro Flt',
    'UnisonSaws',
    "90's EP",
    'SawBrs2006',
    'LoFi Ambi',
    'Saw Lead',
    'MagicPiano',
    'Synth Key',
    'SquLead 06',
    'Old EP',
    'HimalayaFl',
    'Curse',
    'Echo EP',
    'Big Sect',
    'Flare Pad',
    'MG Bass 2',
    'MG SawLead',
    'Dry Str',
    'Poly Synth',
    'Blue EP',
    'Reso Bass',
    'DetuneBrs',
    '5th EP Pad',
    'SquareBass',
    'Hybrid Str',
    'Old Phaser',
    'SuperSaw 1',
    'Pluck Clav',
    '101 Bass',
    'Solo Sine',
    'Arie EP',
    'SftDist Ld',
    'Tre EP',
    'Vinyl Str',
    'Cave 2006',
    'Motion',
    'JP8 Square',
    'Creation',
    'Super-S',
    'Saw Brass',
    'Phase EP',
    'Phase Bs',
    'SuperSaw2',
    'TrancySaw2',
    'POP EP',
    'Treck Pad',
    'Dyno Str',
    'JP8 SquPad',
    'Phase Pad',
    'JP-8 Lead',
    'Tekno Bass',
    'Magma',
    'Old Days',
    'TapeEchoEP',
    'FlareSweep',
    'Sweep Saw2',
    'Saw Stack',
    'Retro Str',
    'EP w/SP',
    'StrMachine',
    'Saw/SquPad',
    'Power Saws',
    "70's EP",
    'Reso Lead',
    'Phase Saws',
    'Explosion'
  ]
};
