import { ExpansionCard } from '../../../types';

export const srx07: ExpansionCard = {
  name: 'Ultimate Keys',
  number: 'SRX-07',
  patches: [
    'Stereo Piano',
    "Gran'Piano",
    'Easy Rocker',
    'Stage Grand',
    'SA Rocker',
    'Padded Pno',
    'Suitcase EP',
    'Real Thing',
    'Fusiontastic',
    'Inspiration',
    'TouchRhdsSRX',
    'Stage SRX',
    'Stage Rhodes',
    'BalladPanner',
    "80's Rhodes",
    'SweetStagePN',
    'PaddedRhodes',
    'Nursery Tine',
    'Sine Rhodes',
    '70s Ballad',
    'Church Mouse',
    'ClaviQRhodes',
    'FlaredTrouzr',
    'Rhodes Bs',
    'Swurly',
    'Dyno-Wurli',
    '60s Bros',
    'Pianohner',
    'Pianette 2K',
    'Cheapy Ep1',
    'Rox St',
    "80's FM",
    'Rhodes EP',
    'Heavens Tine',
    'Sparkle EPno',
    'FirstDigital',
    'Vox Harpsi',
    'Harpsiclav',
    'E.Harpsi',
    'Clav 1 SRX',
    'Clav 2 SRX',
    'VeloClav SRX',
    'Clav 3 SRX',
    'Generic Clav',
    'Clav Pluck',
    'Vintage Clav',
    'Dyno Clav',
    'PhaserClavi',
    'CompClav SRX',
    'MuteClv1 SRX',
    'MuteClv2 SRX',
    'Clav Supremo',
    'Clav By III',
    'Funk Synclav',
    'Quacky Clav',
    'GuitClav SRX',
    'Juno Clavi',
    'PhazynClvSRX',
    'Moogy Pulse',
    'JP8 Clav SRX',
    'HyperClv SRX',
    'Twinkle Bell',
    'Troika Ride',
    'Analog Bell',
    'Goodnite SRX',
    '2.2 SEQ SRX',
    'Vibraphone!',
    'SA Vibe SRX',
    'Blue B SRX',
    'FullPerc SRX',
    'NiceFeel SRX',
    'GreenB /Pdl',
    'Mello',
    'LA Blues SRX',
    '2BorNot2B3 2',
    'Gospel B SRX',
    "Bookin'B SRX",
    'Hush B3 SRX',
    'Real Organ',
    'Tenamos L100',
    'Harm.Organ',
    'Harm.Organ2',
    'Power B SRX',
    'AllStarB3SRX',
    'GoodLord/Mod',
    'CabnetSeries',
    'Absolute B3',
    'Rox-B/Mod',
    'Suitcase B3',
    'BalladB /Mod',
    "70'sKeysMix",
    'Leslied B3',
    'Dyna Hammnd',
    'SaltyDog SRX',
    'Swt&Mllw SRX',
    "Mellow 4'SRX",
    'ZomBee SRX',
    'Perky Twin B',
    'BluesPercSRX',
    'Club Organ',
    '888 +3rd SRX',
    '8888+3rd SRX',
    'Velo Perc',
    'Jazzy B',
    'Gutsy C3',
    'B3 888000004',
    '60s Brothers',
    'FirePerc SRX',
    'PercNorm3rd',
    'PercSoft3rd',
    '858808880SRX',
    'Mad Organ',
    'Touchy B Fst',
    'Souvenirs',
    'R&R B3 SRX',
    'B3Sermon SRX',
    'AllSkate!SRX',
    'BalladB3 SRX',
    'Ultimate B 4',
    'Purple SRX',
    'GimmeSomeSRX',
    'Smoked Water',
    'HardPerc3rd',
    'FuzzheadSRX',
    'Tron B',
    'ShimmerOrgan',
    'AnimalModSRX',
    'SurfMnkysSRX',
    'TelstarOrgan',
    'Continental',
    "Organfest'66",
    'PalisadesSRX',
    'New Riders',
    'The Sham SRX',
    'CrummyOrgSRX',
    'IronFarf SRX',
    'FarfComboSRX',
    'Farfisorium',
    "Farf 8' + 2'",
    'RoxOrgan SRX',
    'DittyDoo SRX',
    'Tranny Organ',
    '2.2 Organ',
    'VS Organ SRX',
    'D OrganSRX',
    'OrganbellSRX',
    'PhazedOrgSRX',
    'Das Limpet',
    'Spanish Gtr',
    'Nylon SoSoft',
    'Nylon on Pad',
    'Moody Nylon',
    'Conquest',
    'Heaven Nylon',
    'In Peace',
    'NashvilleSRX',
    'Caster Delay',
    'RickenstGT',
    'Narnia',
    'Gtr PopArps',
    'Touchy Mutes',
    'Disto-Chunky',
    'Rock Mute',
    'Telemaster',
    'Plugged!',
    'MutedDsBlief',
    'MM Bass /',
    'MMFatSlapSRX',
    'HyperFunkSRX',
    'MillerPopSRX',
    'Funk Bass',
    'Abe 4way SRX',
    'AL3way/NzSRX',
    'ALDarkSlpSRX',
    'John 4waySRX',
    'JPBritSlpSRX',
    'John w/NzSRX',
    '6strngBASS',
    'Big Bad AL',
    'Comp 6tr Bas',
    'AbeLimitrSRX',
    'JP P.Bs 1SRX',
    'JP P.Bs 2SRX',
    "Abe'sP.BsSRX",
    'AL Solid SRX',
    'AL2wayFngSRX',
    'AL SoftBs/Nz',
    'MarcusJB SRX',
    'MM JB SRX',
    'Pick UP SRX',
    'JP Rock SRX',
    'PickedJzBass',
    'BritePickSRX',
    'PhsrMute SRX',
    'DarkPick SRX',
    'Country Mute',
    'FretlessBASS',
    'SoloFls SRX',
    'JP6StrFlsSRX',
    'MM OctFlsSRX',
    'MMSmthFlsSRX',
    'ALFlsSoloSRX',
    'JPSoloFlsSRX',
    'Contrabbasso',
    'InYerFaceBas',
    'BriteUpright',
    'Uplectric',
    'JPSoftAB SRX',
    'JPHardAB SRX',
    'Dry AcB SRX',
    'WildThangSRX',
    'Dist Bs SRX',
    'StickyBs SRX',
    'FunkinWahSRX',
    'Harm A#9 SRX',
    'Harm E69 SRX',
    'SlidesNz SRX',
    'AllSlidesSRX',
    'AllNoisesSRX',
    'Ac.Bs Nz SRX',
    'WildSynth101',
    'SH Dullbass',
    '101 Bass',
    'SH101 Bass',
    'SH-2 Bs SRX',
    'Bassic101SRX',
    'Fat Butt',
    'JP-4 Bs SRX',
    'Systm700 SRX',
    'BigSubBs SRX',
    'TickerBs SRX',
    '202 Bass',
    '101ZapBs SRX',
    'Housy Bass',
    'HousineBsSRX',
    'WooferBs SRX',
    'System100SRX',
    'Low Bass SRX',
    'TB3O3 Reso',
    'MeanderingBs',
    'Acid TB Bs',
    'MonsterMGSRX',
    'Rogue Bs SRX',
    'Classic Bs',
    'Fat Bass',
    'ResoMG BsSRX',
    'MG Punchbass',
    'Spike Bs SRX',
    'WetMG Bs SRX',
    '2-way Bass',
    'Oct stinger',
    'BsPedals SRX',
    'MG PedalsSRX',
    'OB Bass SRX',
    '8VCO Mono',
    'Thick OBass',
    'The Synbass',
    'Dark~~~~BASS',
    'Valve5thBass',
    'Rezidence',
    'OrganSawBass',
    'Organ Bass',
    'SquareBs SRX',
    'SlobbryBsSRX',
    'Super Bs SRX',
    'STronSTringz',
    'TrnStrDrySRX',
    'Tron Vls SRX',
    'MelloVlnsSRX',
    'JP8 Str1 SRX',
    'JP8 Str2 SRX',
    'JP+OB StrSRX',
    'M12 Strings',
    'Wavestr SRX',
    'MemoryMG SRX',
    'Solina SRX',
    'Omni Strings',
    'Big Str SRX',
    'Solo Flute',
    'TouchFlt SRX',
    'StrawberTRON',
    'Flute School',
    'Calli SRX',
    'TpSoloistSRX',
    'Pop Fanfare',
    'Oct Brass',
    'SessnBrs SRX',
    'R&R Bras SRX',
    'SuperTnr SRX',
    'T.Sax f SRX',
    'Cool Sax',
    "Duelin' Saxs",
    'SoftSaxesSRX',
    'AmazngEchSRX',
    'FlaxOstinato',
    '2voiceLd SRX',
    'Hollo Lead',
    'Sinusolo SRX',
    'Shmoog SRX',
    'Sine',
    'SH2000VoxSRX',
    'FM Lead SRX',
    'TrickTailEnd',
    '4 Old Saws',
    'Saw Bowed',
    'VoxSaws Lead',
    'GR500 Ld SRX',
    'LimonaireSRX',
    'NakdCheseSRX',
    'PromarsLdSRX',
    'Sweeze Lead',
    'Homey Lead',
    'MG Lead SRX',
    'Dreams Saw',
    'The Real Pat',
    'H 2 O',
    'PulseLd SRX',
    'Mono FM Lead',
    'VCO OctLdSRX',
    'Saws Lead',
    'Changes',
    'P5 Lead',
    'SH-2&5 Sqr',
    'Cutting Solo',
    'Racy Lead',
    'Speedometer',
    'Rotary Lead',
    'BuzzzzzzzSRX',
    'Telstar Lead',
    'Pattern It',
    'Carbonite',
    'The Pipe 5th',
    'Buzzy Beez',
    'Look Back',
    'Razzert',
    'Raveferenz',
    'SupremeCheez',
    'Exit',
    'MousBoxesCat',
    'Riff the 5th',
    'Ice Man',
    'DncStack1SRX',
    'DncStack2SRX',
    'DncStack3SRX',
    'DncStack4SRX',
    'DncStack5SRX',
    'Euro BrsSRX',
    'ThipsBlipSRX',
    'FaveoravoSRX',
    'Cleanse',
    'Mer',
    'B-lieve',
    'Blue Light',
    'Progress',
    'Modularswirl',
    'Sparkly',
    'Undertones',
    'HappyLFOsSRX',
    'AeroInsctSRX',
    'MC8 Seq SRX',
    'Legato Rip',
    'Steam Valve',
    'Scanner7',
    'Haunted Tron',
    'Experimental',
    'Megatron',
    'Outer Spaces',
    'Martian Bell',
    'Ethereal SRX',
    'Meow 5thsSRX',
    'MantrawavSRX',
    'RSS SpinnerS',
    'Comp Net SRX',
    'SpitBrs SRX',
    'Pro-BrsSRX',
    'OBStabBrsSRX',
    'Pro-5 BrsSRX',
    'Quack BrsSRX',
    'M.MG Brs SRX',
    'FM Brs SRX',
    'DBelpd1SRX',
    'DBelpd2SRX',
    'DBelpd3SRX',
    'KlmbSynthSRX',
    'B Higher',
    'Reflections',
    'VintagLayers',
    'HandleW/Care',
    'StaccHvn SRX',
    'TimefliesSRX',
    'JP6SqKeySRX',
    'CS Squared',
    'MawnlowerMan',
    'Glidiator',
    'Spit Synthie',
    'Raver One',
    'Slop-a-ramaS',
    'Big PWM SRX',
    'WavesyncSRX',
    'T8 Sync SRX',
    'SyncRush SRX',
    'DreaminOfJMJ',
    'Arp Saws SRX',
    'QuixelateSRX',
    'SpikedChzSRX',
    'Planet-S SRX',
    'Iceburg',
    'Old,Warm OBX',
    'Poly 3osc SH',
    'PortaSyn SRX',
    'RazrVCOs SRX',
    'Medusa SRX',
    'PhazeNRG SRX',
    'Build-Up SRX',
    'WavetableSRX',
    'DigiChoirSRX',
    'Rezidue SRX',
    'Combing SRX',
    'PhzslopadSRX',
    'OBThickPdSRX',
    'OBSftPad SRX',
    'RealStrSynth',
    'Rezonant Ens',
    'PG Phaser',
    'SynthOdyssey',
    'Liquid Lunch',
    'JP SquPadSRX',
    'Chewy Pad',
    'Hollow SRX',
    'Too Heaven',
    'Slow 3D Vox',
    'JP Spirit',
    'Classic OB',
    'Aulophony',
    'Dark Shadow',
    'Drawning Pad',
    'Sawed String',
    'R.I.P.',
    'K World',
    'CanyonDreams',
    'Mysterioso',
    'S/HTexturSRX',
    'VP-330ChrSRX',
    'Mellorkestra',
    'Tron Mass',
    'PreSampleVox',
    'Gamma Girls',
    'Lo-Tek Choir',
    'Tron Vox SRX',
    'Vox JX8P SRX',
    'VP303 Arpeg',
    'DrumLP DemoS',
    'Pursuit 90',
    'Arcade 132',
    'SeventhHeavn',
    'TrollDrummin',
    'Chem Burn120',
    'Rockshow 126',
    'T-Pop 132',
    'Valentine 76',
    'Nocturne',
    'Cool At 102',
    'Circuit 112',
    'Hurt 90',
    'Orleans 90',
    'FunkyDrummer',
    'Circuit 90',
    'SweepingLP S',
    'Kick Menu',
    'Snare Menu 1',
    'Snare Menu 2',
    'Snare Menu 3',
    'Hi-Hat Menu',
    'Tom-Tom Menu',
    'Cymbals Menu'
  ]
};
