import { ExpansionCard } from '../../../types';

export const srx09: ExpansionCard = {
  name: 'World Collection',
  number: 'SRX-09',
  patches: [
    'World Sounds',
    'Go2China /C2',
    'Go2India /C2',
    'The Great W',
    'Yuehchin+',
    'Sweet Nylon',
    'Tele R&F',
    'Tubby Baby',
    'HeavenGender',
    'Gamelan Ems',
    'Childwood',
    'La Musette',
    'Essence',
    'Zampona /',
    'GipsyTrumpt/',
    'We Dream }{',
    'Fun WithPerc',
    'GuZheng arp',
    'Feets',
    'World Radio',
    'ClanAdvances',
    'Eastern Tour',
    'Enough!STOP!',
    'Banjo Phrs',
    'Guitar Phrs1',
    'Guitar Phrs2',
    'PdlStl Phrs',
    'Asia UFO',
    'UBeenSoBaa',
    'Didgeri /',
    'WorldGroove',
    'LoopPhrase 1',
    'LoopPhrase 2',
    'TABLA groove',
    'JasonGoEast',
    'Flu&AcompSRX',
    'Split Floot',
    'Hot Salsa',
    'TempBassSolo',
    'CherryFlower',
    'SplitThisSRX',
    'Crane Dance',
    'LostInMists',
    'Qu DiEnsembl',
    'NasalBlossom',
    'Meditation 1',
    'Art Of Feng',
    'Orient xPres',
    'Padded Sitar',
    'No Worries',
    'IntarMel SRX',
    'Ode 2 An Oud',
    'Fugi-man',
    'China pluck',
    'Yuehchin SRX',
    'Kayakeum',
    'Asian Pizz',
    'PiPa SRX',
    'Koto SRX',
    'Shamisen SRX',
    'Sanshin SRX',
    'Yang Qin trm',
    'Yang Qin/Mod',
    'SultanPalace',
    'Marco Polo',
    'Bandolim SRX',
    'K.Bandolim',
    'Afro Harp',
    'Ethnhit!',
    'OctaHarp+',
    'St.GuZhngSRX',
    'Zheng Zither',
    'Distance',
    'Mandolin/Mod',
    'Mandolin',
    'Mando Club',
    'MdlnTrmStSRX',
    'Drone Sitar',
    'Conch&Sitar',
    'Punjab Rocks',
    'Pas2IndiaSRX',
    'Rain Drone',
    'SitarGlisSRX',
    'Tambura SRX',
    'TambDroneSRX',
    'St.SanturSRX',
    'SanturTrmSRX',
    'Santur /Mod',
    'Canton',
    'HamrDulcimer',
    '3D Dulcimer',
    'Zither',
    'Magic Pluck',
    'Biwa SRX',
    'Biwa Menu',
    'BerimbauMenu',
    'Berimbau',
    'JawHarp Menu',
    'Steel Rhythm',
    'SoloSteelGtr',
    "N'Ville Soft",
    'Spruce Top',
    'Procssd AGtr',
    'High Strung',
    'Compresd D18',
    'String',
    'Mixed 12Str1',
    'Mixed 12Str2',
    'Ac Gtr 12stg',
    'No Borders',
    'Loose 12Str',
    'Living R.Gtr',
    'Dobro Modro',
    'ResonatorGtr',
    'Ac.Gtrs SRX',
    '2 Players',
    'Solo RequGtr',
    'Loose Nylon',
    'AcousticBros',
    'So Sad Nylon',
    'Chinese Duo',
    'ChugRunTrSRX',
    'Chung Ruan',
    'ChungRuanSRX',
    'Bottom Ruan',
    'RuangGtr SRX',
    'Oud SRX',
    'BlugrsSldSRX',
    'Guitaro SRX',
    'Natural Tele',
    'Psyche Tele',
    'Coral',
    'Chorus Twang',
    'Pick Licker',
    'CleanStrtSRX',
    'Velo SRX',
    'Right Funky',
    'Comp Muted',
    'E.GtrMt SRX',
    '335VelMt SRX',
    'Wide Guitar',
    'Dob-Compress',
    'Nice Twelvey',
    'RotaryCrunch',
    'FastRotrySRX',
    'EGDynaPikSRX',
    'BackingEGSRX',
    'Room Slide',
    'Pedal Steel',
    'Phased P.Stl',
    'PureSteelSRX',
    'MutedAmbient',
    'GtrFX Menu',
    'LP Gtr SRX',
    'Tele-Funfken',
    '&Cabinet',
    'Tele Licker',
    'Short & Long',
    'NewBeginning',
    'Bouzouki',
    'Bousoukhit!',
    '3ChdStrumSRX',
    'Strum Poetic',
    'Strum Away',
    'Banjo-Mando',
    '5StringBanjo',
    'Banjo SRX 1',
    'Banjo SRX 2',
    'Banjo SRX 3',
    'Fiddle',
    'Fiddle 2002',
    'FiddleSwitch',
    'Fiddle Sect.',
    'FiddleStacto',
    'AsianOrcPizz',
    'AJapaneseInn',
    'Deep Blue',
    'Ethnic Ens',
    'ChinesOrcSRX',
    'ErHu / SRX',
    'ErHuSolo SRX',
    'ErHu Ld SRX',
    'FiddleFXmenu',
    'ViolnSoloSRX',
    'Comp BabyBss',
    'Baby Bass',
    'Comp Fingerd',
    'Jazz Fing.BS',
    'Live Bass',
    'Flango Bass',
    'Bass Oddesy',
    '6Str Bs SRX1',
    'Muted Bass',
    '6Str/Mt SRX',
    'PickBsHd SRX',
    'PickedBs SRX',
    'Tub Bass',
    'GuitarnBsSRX',
    'GtrrnOct SRX',
    'PacificDream',
    'Meditation 2',
    'HybridKemong',
    'Purify',
    'Asia Bells',
    'Rama Cym SRX',
    'Bell Orchest',
    'Sacred Bells',
    'Spokes',
    'Winter Bells',
    'Wind Bells',
    'BelAngk SRX',
    'Tcheekolyna',
    'Wood EPiano',
    'Kalimba',
    'Kalimbatch',
    'VelAfro SRX1',
    'BsKalimbaSRX',
    'LogDetunrSRX',
    'Baateri SRX',
    'Balafon SRX',
    'Asian Wood',
    'Mellow tone',
    'Glas Mlt SRX',
    'SteelDr SRX1',
    'SteelDr SRX2',
    'Gendrous SRX',
    'BonangGamSRX',
    'VelAfro SRX2',
    'TemleMetlSRX',
    'Kemong / SRX',
    'Kane / SRX',
    'JeGong / SRX',
    'Jegogn / SRX',
    'Jublag / SRX',
    'Reyong / SRX',
    'Pemade / SRX',
    'Cajun',
    'D.Accordion',
    'SquezeBoxSRX',
    'Squeeze Box',
    'St.AcdOp SRX',
    'AcdionOp SRX',
    'Acd ffOp SRX',
    'St.AcdCl SRX',
    'Bluesy',
    'HarmonicaSRX',
    'CuntryHrpSRX',
    'Sessn HrpSRX',
    'Esraj&Mizmar',
    'Before Time',
    'Gagaku Ems',
    'Mizmar solo',
    'PiriSolo SRX',
    'Shahnai SRX',
    'HichirikSRX',
    'Bagpipes SRX',
    'Sheng / SRX',
    'Suona / SRX',
    'VillageDance',
    'Indian Ens',
    'Nature Loves',
    'PanPipes SRX',
    'Sad Pipe',
    'Shell blow',
    'Desert Flute',
    'Zampona',
    'Isolation',
    'Ocarina',
    'New IndFlute',
    'Qu Di Vi',
    'Bang Di Vib',
    'New Kawala',
    'BreathyIndia',
    'New Shaku',
    'Shakuhachi',
    'DreamInColor',
    'TwinHillyLd',
    'Snake Eyes',
    'Latin Trumpt',
    'MariachiTpts',
    'Trumpets',
    'GrowlWah/Mod',
    'Muted-Grw /',
    'SoloTuba SRX',
    'LatinTubaSRX',
    'World Orch',
    'Stab&Hold',
    'Indian Radio',
    'Wide Brass',
    'Trombones',
    'Brass Snapz',
    'Brass sfzzZZ',
    '2Tp+Tbn SRX',
    'MemphisHORNS',
    'SectStactSRX',
    'LatinBrasses',
    'Hit & Fall',
    'BrsChdSRX',
    'BrsChdMi9SRX',
    'BrsChdMj9SRX',
    'Blow Pad',
    'Ceremony',
    'Glasses',
    'Ambiccordian',
    'DroneFlanger',
    'Rock Gods',
    'ScotlandLass',
    'Dry Fishes',
    'SteroidBrass',
    'Soul revived',
    'Rain Pad',
    'Rising Sun',
    'Ethnopad',
    'Ethno Strngs',
    '& Thieves',
    'TromboSynthy',
    'GrandExaltd1',
    'Sun Dog',
    'TechnoSpirit',
    'Play Softly',
    'WorkerBeetle',
    'Glass Cut',
    'GuruTronics',
    'DubJazz Trip',
    'Meditation 2',
    'Political',
    'G`day Mate',
    'Mission',
    'Jegorgan',
    'Dyno Conga 1',
    'Dyno Conga 2',
    'Congas+Bongo',
    'DynTimbale 1',
    'DynTimbale 2',
    'TimbaleCuica',
    'Dyno Surdo',
    'Rhythm Sect',
    'Rainstick',
    'Clap & Snap',
    'CowbellRandm',
    'Karachi-Man',
    'That Was Zen',
    'StreetParade',
    'BUK',
    'Gongs',
    'Chenchen /',
    'WisdomWithin',
    'Tabla+',
    'DrumsScene',
    'Doholla Fun',
    'AfricanRhtms',
    'Big Logs SRX',
    'WarDrums SRX',
    'Samba Menu',
    'Shaker Menu',
    'Caixa Menu',
    'Cowbell Menu',
    'JapanPrcMenu',
    'Kabuki Menu',
    'KwangwariSRX',
    'Tuzumi / SRX',
    'KoreaPrcMenu',
    'ChinaPrcMenu',
    'China Menu',
    'ChinaGongSRX',
    'Sanba / SRX',
    'St.ShouBoSRX',
    'AsiaCym Menu',
    'Gong Menu',
    'Gamelan Menu',
    'GamlnPrcMenu',
    'BigBazar SRX',
    'Udu Pot Menu',
    'TablaBy Menu',
    'Rek Menu',
    'Dholak Menu1',
    'Dholak Menu2',
    'Dhol Menu',
    'Egypt Tablah',
    'Madal Menu',
    'AfropercMenu',
    'CommSatelite',
    'Amazone',
    'Tasman Sea',
    'Ethnic FX 1',
    'Ethnic FX 2',
    'SpacetualBoy',
    'Crystal',
    'SpaceLuvSick',
    'HitAscension',
    'Nervous Man',
    'Silk Stream',
    'DerangedMind',
    'PolyDrone',
    'TequillaWorm',
    'GlistenToYou',
    'Dream Harp',
    'Waterfall',
    'Gender 3D',
    'Doom Drum',
    'Stalker',
    'PlasticBones',
    'PakistanVibe',
    'ThusSpokeZtr',
    'Kalissando',
    'Rain Forest',
    'AfropunchSRX',
    'Dance Tape',
    'Zaghruta SRX',
    '1,2,3,4! SRX',
    'Voices SRX',
    'Voice Menu 1',
    'Voice Menu 2',
    'Voice Menu 3'
  ]
};
