import { ExpansionCard } from '../../../types';

export const srx12: ExpansionCard = {
  name: 'Classic EPs',
  number: 'SRX-12',
  patches: [
    'Pure EP1',
    'Lo-Fi EP1',
    'Pure EP2',
    'Phaser EP1',
    'Soft Wurly',
    'Pure Wurly',
    'Pure Clav DB',
    'Pure Clav CB',
    'PhaseClav CB',
    'Wah Clav CB',
    'Comp Clav CB',
    'PureClavMtCB',
    'St.Trem EP1',
    'St.Trem EP2',
    'Chorus Wurly',
    'Chorus EP1',
    'Chorus EP2',
    'Dp-Cho EP1',
    'Dp-Cho EP2',
    'Soft EP1',
    'Soft EP2',
    'Phase Wurly',
    'Hard EP1',
    'Moving EP1',
    'EP1 w/FM',
    'EP1 w/VOX',
    'EP1 w/STR',
    'EP1 w/PAD',
    'Flanger EP1',
    'Flanger EP2',
    'FlangerWurly',
    'Melodic EP1',
    'Amped EP1',
    'Amped EP2',
    'Lo-Fi EP2',
    'Lo-Fi Wurly',
    'ModDly EP1',
    'ModDly EP2',
    'Dual EP1',
    'Dual Wurly',
    'Enhance Clav',
    'Peaking Clav',
    'Dual Clav DB',
    'Dual Clav DA',
    'Dual Clav CB',
    'Dual Clav CA',
    'DualClavMtDB',
    'DualClavMtCB',
    'PhaseClav DB',
    'PhaseClvMtCB'
  ]
};
