import { ExpansionCard } from '../../../types';

export const srx02: ExpansionCard = {
  name: 'Concert Piano',
  number: 'SRX-02',
  patches: [
    'PremierGrand',
    'Steady Grand',
    'DynamicGrand',
    'Concert Hall',
    'Bright Grand',
    'Classical',
    'SoftPdlGrand',
    'OnMicPremier',
    'OnMic Bright',
    'OnMicSoftPdl',
    'Premier Mono',
    'Bright Mono',
    'SoftPdl Mono',
    'Mellow Piano',
    'Enhanced Pno',
    'Comp.Piano',
    'HonkytonkPno',
    'NewAgeGrand1',
    'NewAgeGrand2',
    'Requiem',
    'Soundscape',
    'Grand w/Str',
    'Concerto 1',
    'Concerto 2',
    'SoftpadGrand',
    'Synpad Grand',
    'Vox Grand 1',
    'Vox Grand 2',
    'Oohs Piano',
    'Air Grand',
    'GtrPad Grand',
    'PhasePad Pno',
    'HeavenPadPno',
    'Somber Pad',
    'Wet Chorus',
    'Nylon Grand',
    'FM EP Grand',
    'Bell Grand',
    'Bellvox Pno',
    'StackedGrand',
    'Hard Stack 1',
    'Hard Stack 2',
    'PianoBrass',
    'PianoBrs fff',
    'Gig Split 1',
    'Gig Split 2',
    'Gig Split 3',
    'Throb Piano',
    'Feedback Pno',
    'Eastern 5th'
  ]
};
