import { ExpansionCard } from '../../../types';

export const srx10: ExpansionCard = {
  name: 'Big Brass Ensemble',
  number: 'SRX-10',
  patches: [
    'Pop Brs Sect',
    'Pop Brs Stac',
    'Pop Brs Fall',
    'Trumpet Sect',
    'Tp Sect Stac',
    'Tp Sect Doit',
    'Mute Tp Sect',
    'MtTpSect Stc',
    'C Tp Section',
    'C TpSect Stc',
    'C TpSect Tri',
    'TromboneSect',
    'Tb Sect Stac',
    'Tb Sect Fall',
    'Horn Section',
    'HornSect Stc',
    'HornSect Rip',
    'Tuba /',
    'Tuba Stacc',
    'Mezzo Pop',
    'Mezzo Pop WS',
    'DynaBrass M',
    'Smooth Brass',
    'Oct PopBrass',
    'PopBrass Sfz',
    'Stac PopSect',
    'PopBrs ShtFl',
    'PopBrs LngFl',
    'PopBrass Rip',
    'PopBrs /Fl 1',
    'PopBrs /Fl 2',
    'ShortBrs /Fl',
    'Smooth Tps',
    'Tpt Section',
    'Tpt Sect WS',
    'Tpt Sect M',
    'Mild Tp Sect',
    'Tp Sect Sfz',
    'Tp Sect Fall',
    'TpSect RipFl',
    'TpSect RipCp',
    'TpSect Shake',
    'Trumpets /Fl',
    'Trumpts/Shak',
    'Trumpts/Doit',
    'ShortTps /Fl',
    '..the Ripper',
    "Don't Doit!",
    'MuteTpSect S',
    'MuteTpSect M',
    'Mild MuteTps',
    'Smooth C-Tps',
    'C-Tps w/Vib',
    'C-Tp Sect',
    'C-Tp Sect WS',
    'C-Tp Sect M',
    'Mild CTpSect',
    'CTp Sect Sfz',
    'Tripoli',
    'Mainly Stacc',
    'C Tpts /Trit',
    'Smooth Tbs',
    'Mild Tb Sect',
    'Tb Sect',
    'Tb Sect WS',
    'Tb Sect M',
    'Tb Sect Sfz',
    'Tb Sect Rip',
    'Tb Sect /Fl',
    'ShortTbs /Fl',
    'ToodleAction',
    'Smooth Horns',
    'Horn Sect',
    'Horn Sect WS',
    'Horn Sect M',
    'EmotiveHorns',
    'Mild Horns',
    'HornSect Sfz',
    'HornSect/Rip',
    'HornSwitcher',
    'Mild Tuba',
    'Tuba Sect WS',
    'Tuba Sect M',
    'TubaSwitchOn',
    'Tp+Tb Sect /',
    'CTp+Tb Sect/',
    'LOUD OK?!',
    'Hey You Mute',
    'FullOnBrass',
    'Blend Brass',
    'LR Mix Stacc',
    'Warm Tp Sect',
    'Dyna Section',
    'Warm Horns',
    'Schizo Brass',
    "Don't hit me",
    'DiminerBrass',
    'Wild Niner',
    'Mid Thirties',
    'BrsStac Echo'
  ]
};
