import { ExpansionCard } from '../../../types';

export const srx08: ExpansionCard = {
  name: 'Platinum Trax',
  number: 'SRX-08',
  patches: [
    'Autopilot',
    'ElasticHouse',
    'Smash Beat',
    'SawPortaLead',
    'Pure Bass',
    'Jazz Parrotz',
    'Nicer Slicer',
    'Masssive',
    'Trance Line1',
    'Subtle Pads',
    'Look Back',
    'VesperTONE',
    'Hit&FX Menu',
    'Crowd',
    'Hop Chop SRX',
    'Skid',
    'Predator',
    'Scream! SRX',
    '8 BPM',
    'X-Tronic SRX',
    'Trans SRX',
    'AcidRiff',
    'FullHous SRX',
    'Funk E',
    'Le Punk',
    'TekOp SRX',
    'Cauldron',
    'Punken',
    'Blitzkrieg',
    'Hauln',
    'Antenna',
    'Barry',
    'Slipn',
    'UndrTheStair',
    'Slam',
    'Only Human',
    'BAD',
    'Drama',
    'Mon',
    'McSick',
    'Meanstreet',
    'Meow',
    'Blvd',
    'Coder',
    'iROBOT',
    'Lifeform',
    'Haiti',
    'Hiphouse',
    'OW!',
    'CHI',
    'Miami',
    'Swing',
    'ObsessionSRX',
    'PJ',
    'Sky',
    'Aerosol Can',
    'Triggroove',
    'De Final CUT',
    'Chemiclspill',
    'DerangedBeat',
    'Cubit Dance',
    'Multi Level',
    'Random Beat',
    'Sonic Beat',
    'Fuzzy Wuzzy',
    'Cyclone',
    'Electrolux',
    'Bongo Congo',
    'Tricky Beat',
    'Windmill',
    'SlamSymphony',
    'Time Pulse',
    'TrainAComin',
    'House Rules',
    'Mother Ship',
    'YankyDoodlDo',
    'Elven Kbds',
    'DnB SRX',
    'Beat Menu 1',
    'Beat Menu 2',
    'TarzanBottom',
    'Subporter',
    'Subsonics',
    'Sub Bass',
    'HiLo/Mod',
    'Bass Ment 1',
    'Bass Ment 2',
    'TB SawBs SRX',
    'TB OwBs SRX',
    'Acidic Testz',
    'Talk Bass',
    'VocoBass SRX',
    'Massive Bass',
    'TB Sqr SRX',
    'SQR Reso Bs',
    'SH-5 Synbass',
    'Juno Bs SRX',
    'SlippyBs SRX',
    'Arrpy Bs SRX',
    'TB / SRX',
    'TB-notTB SRX',
    'Si<n>ck Bass',
    'Deep Fat Bas',
    '7 bit bass',
    'DistortObass',
    'Double Bass',
    'Killer Bass',
    'Dancer Bass',
    'Rave Bass',
    'Big Bad Bass',
    'Fat FM Bass',
    'JackYourBody',
    'Solid Bs SRX',
    'Thick Bass',
    'Deep Bass 2',
    'Bassamatazz',
    'Juno 6 Bass',
    'Da JuBs SRX',
    'Fizzle Bass',
    'Ringin` bass',
    'No Rez 4 You',
    'Boomer',
    'OrgAtk Bass',
    'WahBassMod X',
    'LFO SqrBass',
    'FallBend Bs',
    'Hocket Bass',
    'FatBs / SRX',
    'LoFi A.BsSRX',
    'ProcesBs SRX',
    'Solo flight',
    'Euro mix SRX',
    'Nitty Gritty',
    'Alias Lead',
    'Old Fi',
    'Dist-O-Matic',
    'Lead Dirt',
    'RetroRave',
    'Skreech Lead',
    'Outrage',
    'HipassTB SRX',
    'TB Squared',
    'TB Saw',
    'DistortedSaw',
    'Nail Driver',
    'Nasty',
    'Dance Baby',
    '5th Rave',
    'Auto',
    'Sine me in',
    'SoloSin SRX1',
    'SoloSin SRX2',
    'Piccolo solo',
    'Ana Flt SRX',
    'JUResLd SRX1',
    'Med Solo SRX',
    'MilkyWay SRX',
    'Shalot SRX',
    '3D Lead',
    'JUResLd SRX2',
    'Gringeley',
    'EuroSteroidz',
    'Operator',
    'NeverStopRvn',
    'TheSteamRoks',
    'TechnoAttack',
    'Formantz',
    'SRX Talker',
    'Nanite Pops',
    'TechnoAmbint',
    'Ringywig',
    'OrganOran',
    'Piddlee-Dee',
    'Cool Beam',
    'First Synth',
    'Santaz House',
    'Sub Melodic',
    'Landing Crew',
    'Chime Blocks',
    'Chordon Bleu',
    'Porter Rix',
    'PhenomenaSRX',
    'Club Hit',
    'ChrdMaj7 SRX',
    'ChrdMin7 SRX',
    'CordintheAct',
    'MetroPoly',
    'Lava Flow',
    'Panorama',
    'Nautilus',
    'Sliced Bread',
    'Time Machine',
    'Ana Logic',
    'Bass & More',
    'In The Lab',
    'Galaxia',
    'Charmer',
    'BrainWaveSRX',
    'Replicants',
    'Speak Delay',
    'Location',
    'Cyber SRX',
    'EtheraltySRX',
    'IceDream SRX',
    'UpperStepper',
    'Padestrians',
    'Starlite XV',
    'Trance Line2',
    'Eurosynth',
    'Fat JP',
    'EuroDnc SRX1',
    'EuroDnc SRX2',
    'XpressiveSRX',
    'Organ-ized',
    'Juno Pluck',
    'Juno Plucked',
    'Rubberized',
    'Intense Vibe',
    'Intense Euro',
    'Generation e',
    'NewSkool s',
    'SyncDiffrent',
    'Kill Eyeopee',
    'FM Ringer',
    'Live at 5',
    'Octo',
    'Alpha Fizz',
    'FunkyJunoHrp',
    'Steel Piano',
    'Velorez 0',
    'JU Keys SRX',
    'Euronal Syn',
    'Daft',
    'Neurotic Syn',
    'Deep Forest',
    'Pip Square',
    'Funky Pluck',
    'Tight TB',
    'Saw Yr Point',
    'Shortsawz',
    'Tropical Syn',
    'JU Pluck SRX',
    'TB AtkDst',
    'Amber',
    'Vox Switcher',
    'Juno Strings',
    'DetuneSawStr',
    'Wavebreaker',
    'Vintage Pad',
    'Glitz',
    'Discrete',
    'VntageRevSRX',
    'Explore SRX',
    'AfterPad SRX',
    'Euro Strings',
    'Powder',
    'JU&JP PhsSRX',
    'Lost In Time',
    'Europad',
    'Avalon SRX',
    'Dreames SRX',
    'SirenSng SRX',
    'CricketChoir',
    'TV Drama',
    'Elven Times',
    'TwilightPad',
    'WarmerPd SRX',
    'SoftStrngSRX',
    'AlphaWavePad',
    'Micromusic',
    'LitleDowners',
    'Fulcanelli',
    'Galaxial',
    "It's Outside",
    'Alien Life',
    'Prey',
    'Transender',
    'Steel Drone',
    'Trissle',
    'Dimensions',
    'TuneBrethSRX',
    'Sonic Saucer',
    'Alter Native',
    'Evolution',
    'Outer Space',
    'Hyperspace',
    'WhaleUnitSRX',
    'Orcafreq SRX',
    'CrepedOutSRX',
    'Bombay Drone',
    'Fathoms SRX',
    'MothrshipSRX',
    'Cleansers',
    'Vinylprelude',
    'Turbine SRX',
    'Thrilling',
    'Bada Boing',
    'Confused',
    'Revolution#9',
    'Bugstep Noot',
    'Crotals',
    'Big Bang *',
    'South Sahara',
    'MunchiesPt',
    'AlternSawSRX',
    'ElctroJamSRX',
    'Zaps',
    'B-Movie',
    'ScientistSRX',
    'Siren',
    'Sliderz SRX',
    'Krashead',
    'Iron Hit SRX',
    'DrumMeltDown',
    'TR Synhit',
    'Pit People',
    'Mad RHyThM',
    'ModrnLifeSRX',
    'BigBang SRX',
    'GateKeperSRX',
    'UndrWaterSRX',
    'TheWetSet',
    'DJ stuff SRX',
    'Skratchy SRX',
    'RPM SRX',
    '3D Turntable',
    'RadioBrekSRX',
    'Faze Gt&Bass',
    'Hse Stb',
    'Full Force',
    'Soho Clubs',
    'GarageChdSRX',
    'Crap Stab',
    '2am-am',
    'Hit&Run SRX',
    'HIT in face',
    'LoFiHits SRX',
    'Next Stab',
    'Brazzer LoFi',
    'Big Stab SRX',
    "'s Tpt SRX",
    'BrsFall SRX',
    'Slammer',
    'Tribal Disco',
    'DiscoStr Hit',
    'Break HIT',
    'Cwisp SRX',
    'NYC Club SRX',
    'Tape Stops',
    'LoFi Subsine',
    'Maj/Min /',
    'Techno Logic',
    'Slam Hit',
    'Image BOOOM!',
    'Keep Clubing',
    'Techno Riff1',
    'MySweetHouse',
    'LateNiteTunz',
    'Moody Vibes',
    'Exit 2',
    'Massive',
    'Techno Riff2',
    'Metalsmith',
    'Meteor Pelt',
    'China White',
    'NewTech D&B',
    'Water Plug',
    'Tribal Steel',
    'Tech Pno SRX',
    'LightPno SRX',
    's Pno SRX',
    '1FingrPnoSRX',
    'Pf/Key Menu',
    'Substitute',
    'HiphopEP SRX',
    'Assembled',
    'MelowTremSRX',
    'EchoRhds SRX',
    'GaragesSRX',
    'Wurlpool',
    'Lo Fi Wurli',
    'Dance Organ',
    'Juno Org SRX',
    'Clubed Organ',
    'Pop B',
    'Vel Syn Org',
    'SpenderOrgan',
    'Tines&Wheels',
    'Thick Organ',
    '1FingrOrgSRX',
    'Shorty Organ',
    '1FingrShrOrg',
    'Clav-ClubSRX',
    'DanceClavSRX',
    'CeremonyBell',
    'AnaBells SRX',
    'Guitar Stuff',
    'WahWahMelSRX',
    'GTRPowerSRX1',
    'GTRPowerSRX2',
    'FakeHead Hit',
    'Distinctive',
    'Gtr&BassMenu',
    'Pizz Xpress',
    'Tek Pizz SRX',
    'Stringy Stab',
    'CSBrass',
    'Fat Brass',
    'Talk Box SRX',
    'TekMusic SRX',
    '1.2.3.4. SRX',
    '4 x4 SRX',
    'Baby...? SRX',
    'Vox Menu 1',
    'Vox Menu 2',
    'MelodicDrums',
    'Drumpeopled1',
    'Drumpeopled2',
    'Drumpeopled3',
    'KitTek.drmFX',
    'Hardcore Hit',
    'Kick Menu 1',
    'Kick Menu 2',
    'Kick Menu 3',
    'Snare Menu 1',
    'Snare Menu 2',
    'Snare Menu 3',
    'Snare Menu 4',
    'Snare Menu 5',
    'HiHat Menu 1',
    'HiHat Menu 2',
    'HH&Cym Menu',
    'Cymbal Menu',
    'Tom Menu',
    'Clap Menu',
    'Chord',
    'Conga 3D',
    'Slow Chimes',
    'Dirty Sox',
    'ExtremPercus',
    'Pure Tribal',
    'TeknoTriangl',
    'Tamb&SkrMenu',
    'Cow&Rim Menu',
    'Perc Menu 1',
    'Perc Menu 2',
    'Perc Menu 3',
    'Perc Menu 4'
  ]
};
