import { ExpansionCard } from '../../../types';

export const srx04: ExpansionCard = {
  name: 'Symphonique Strings',
  number: 'SRX-04',
  patches: [
    'Epic Strings',
    'sfz! Crsc/sw',
    'Trem/sw Fine',
    'Fast Stac/sw',
    'Str Attack',
    'Full Pizz mp',
    'Violins ^/sw',
    'Violas ^/sw',
    'Celli ^/sw',
    'Basses ^/sw',
    'Fast Section',
    'F.Str ^/sw',
    'SymphStrings',
    'SymphStrngs2',
    'Vibrato /Aft',
    'Expressimo',
    'Spc release',
    'Hall Strings',
    'Warm Section',
    '4Section ^',
    '4Section Vib',
    'Sad Strings2',
    'Pizz&ArcSplt',
    'So Swell',
    'Full Section',
    'Vibrato /sw',
    'Octave ^',
    'Full Sect 2',
    'Attack Sect',
    'Velo Strings',
    'Full Tremolo',
    'Trem Decresc',
    'Tension Trem',
    'F.StrTrm/Mrc',
    'F.Str Trm/sw',
    'Trm /Mod&Aft',
    'F.Str/ModTrm',
    'Spc Marc /sw',
    'WarmStaccSec',
    'StackNirvana',
    'Spc Sect.8va',
    'Spc-Mrc /sw',
    'Mrc-Spc /sw',
    'Full Spc /sw',
    'Marc & Pizz',
    'PizzL+SpiccR',
    'Pizz Sect',
    'Full Pizz pp',
    'Full Pizz ff',
    '4Sect. Pz ff',
    'Double Pizz',
    'sfz! Vln /sw',
    'Violin Sect1',
    'Violin Sect2',
    'Violin Sect3',
    'Warm Vln Sec',
    'GrandVln&Vcs',
    'Vln Sect mp',
    'Slow Atk Vln',
    'Vln/Mod Pizz',
    'Vln Stc/Mrc',
    'Vn Piz/Spcff',
    'Vln Marcato',
    'Vln Pizz /sw',
    'sfz! Va /sw',
    'Viola Sect 1',
    'Viola Sect 2',
    'Va Stc/Mrc',
    'Va /Mod Pizz',
    'Va Marcato',
    'Va Pizz /sw',
    'sfz! Vc /sw',
    'Cello Sect 1',
    'Cello Sect 2',
    'Warm Vc Sect',
    'Vc Pizz /sw',
    'Vc /Mod Pizz',
    'Vc Marcato',
    'Vc Stc/Mrc',
    'Vc Piz/Spcff',
    'sfz! Cb /sw',
    'Cb /Mod Pizz',
    'Bass Sect 1',
    'Cbs Marcato',
    'Cbs Stc/Mrc',
    'Cbs Pizz /sw',
    'Symphonique2',
    'Soundtrk Str',
    'LargeStrings',
    'Slow Atk Str',
    'LushStrings2',
    'Pop Strings',
    '102 Violins',
    'MultiStakato',
    'Spicatto Arp',
    'Dim. Pizz',
    'RhythmicPizz',
    'Harp StrPad',
    'Trem-Guitar',
    'Baroque Ens2',
    'ImitatEP Pad',
    'Daybreak Ens',
    'Grand Unison',
    'Va Sect&Glkn',
    'SRX Symphony',
    'XV Orchestra',
    'Full Orch 1',
    'Orc with Str',
    'Symphnic Orc',
    'Strings&Hrns',
    'Strgs&Hrns 2',
    'Octa StrEns',
    'Antique Str',
    'SweepSectStr',
    'Stereo Tron!',
    'Horror Str.',
    'DanzSurround',
    'Ether Strngs',
    'MoveFX Str',
    'Phase /Aft',
    'PhazeStrngs2',
    'Reverse Str2',
    'Haunted',
    'Rewind Vln',
    'Synthy Sweep',
    'Ripple',
    'Mystery 2',
    'Rising STR'
  ]
};
