import { ExpansionCard } from '../../../types';

export const srx06: ExpansionCard = {
  name: 'Complete Orchestra',
  number: 'SRX-06',
  patches: [
    'WarmVlns SRX',
    'Legato Vlns',
    'NaturalVlnsS',
    'Agitato Vlns',
    'Vlns-Spc /',
    'Vl&Va Spicct',
    'Arco Vas SRX',
    'Agitato Vas',
    'Vlas-Spc /',
    'Marc Vas SRX',
    'Vc Sec mf',
    'Fast Cellos',
    'Vcs Legato',
    '3 Cellos',
    'Cellos',
    'CelloSectMrc',
    'Marcato Vcs',
    'Agitato Vcs',
    'Vcs+Cbs SRX',
    'Arco Vcs+Cbs',
    'Thick Basses',
    'Cb Sect SRX',
    'WideBasses S',
    'Agitato Cbs',
    'BIG StrgEns',
    'Big Strings2',
    'Orch p',
    'Orch p>f/Mod',
    'StrsArco SRX',
    'StrSwel/ModS',
    'StStrOrcp/fS',
    'SlowResinStr',
    'Adagio Strs',
    'LegatoStrngs',
    'Intim StrSec',
    'DramaStrsSRX',
    'St Str p/f',
    'SlowEpic Str',
    'Real Strings',
    '4Seasons SRX',
    'VlVaVcCb SRX',
    'StudioString',
    'Quartet SRX',
    'VibSwStrings',
    'Str Swell',
    'OuvertureSRX',
    'Cluster Sect',
    'Velo Str SRX',
    'Agitato to 0',
    'DynaMarc SRX',
    'VivaceStrSRX',
    'Agitato STR',
    'STR SpiccSRX',
    'StacctoSectn',
    'Spicc/releas',
    'STR Marcato',
    'Big Marcato!',
    'Spicc Sect',
    'Spc+Pz/rleas',
    'Piz-Spc /',
    'RoomPizz SRX',
    'Stage Pizz',
    'Nite Pizzico',
    'VIOLIN solo',
    'Solo Vln /',
    'Solo Violin',
    'Sad S.VlnSRX',
    'Solo Viola',
    'AgitatoVaSRX',
    'Solo Cello 1',
    'Solo Cello 2',
    'The V Cello',
    'Solo Vc /',
    'Marcato Vc',
    'Vln&Vcl',
    'Solo Cb /',
    'Tape Orc SRX',
    'Tape Str SRX',
    'Old Tale',
    'Mellow Tape',
    'Cystaline Pd',
    'SynStrings',
    'Full Orc SRX',
    'St.OrcUniSRX',
    'OrchUnif SRX',
    'GRAND OrcSRX',
    'WavinGoodbye',
    'DynOrchestr1',
    'Pathetique',
    'Oboes & Sect',
    'SlowEpicOrch',
    'Grand Tutti',
    'Ultimate Orc',
    'SuspenceOrch',
    'Tremolo /',
    'TremOrc /Mod',
    'ORC full+BD',
    'Finally Orch',
    'Orch & Choir',
    'NowWeAreFree',
    'Too Tense',
    'OrchestrlSRX',
    'DynOrchestr2',
    'GiantOrchest',
    'Strngs&Horns',
    'Full Orch 1',
    'Full Orch 2',
    'Full Orch 3',
    'End Titles',
    'HornStrs SRX',
    'SRX Full Orc',
    'Harp & Flute',
    'Celesta&Flt',
    'ProkofievSRX',
    'MassInCeeSRX',
    'PentatnicSRX',
    'DawnSynphony',
    'Bad Ending',
    'Epic Ending',
    'Catwalk',
    'OrchStaccato',
    'Staccato SRX',
    'OrchHitStack',
    'Dynam Hit',
    'MondoHit SRX',
    'OrchHit SRX',
    'OrcHitMajSRX',
    'OrcHitMinSRX',
    'OrcHitDimSRX',
    'Big Hit Maj1',
    'Big Hit Maj2',
    'Big Hit Min',
    'Big Hit Dim',
    'Sfz! Hit-Maj',
    'Sfz! Hit-Min',
    'Suspense',
    'Hit/Off-Maj',
    'Trem Hit-Maj',
    'Trem Hit-Min',
    'Trem Hit-Dim',
    'Orc/Prc 5-1^',
    'Drama Stab',
    'Maj Concern',
    'OrcGlsMajSRX',
    'OrcGlsMinSRX',
    'Harp Up Hit',
    'Harp Dn Hit',
    'BrassStabSRX',
    'Finale',
    'Tuned HIT',
    'YourMissionS',
    'Big Hit SRX',
    'HorrorHitSRX',
    'Perc Hit',
    'BrassFallSRX',
    'Tp Fall',
    'BrsStacc SRX',
    'Finale SRX /',
    'Orch Piccolo',
    'Picc Vel Tr',
    'Piccolo Trio',
    'Orch Flute',
    'Vibra Flute',
    'FluteAtm/Aft',
    'Picc/Fl 8va',
    'Double Flute',
    'Fl/EH Usn',
    'Calliope SRX',
    'DynoCelt SRX',
    'Ethnic Flute',
    'AmbiFluteSRX',
    'T.WhistleDly',
    'TinWhistle',
    'Sop Recorder',
    'Tnr Recorder',
    'Whistle SRX',
    'Solo Clari',
    'Unison Clari',
    'Orch Clar',
    'Bs Clairenet',
    'Orch Bs Clar',
    'Cl/Bs Cl 8va',
    'Fl/Cl Usn',
    'Fl/Cl 8va',
    'Orch Oboe',
    'Sweet Oboe',
    'Cor Oboe',
    'OBOE Solo',
    '2 Close Oboe',
    'Orch Eng Hrn',
    "Horn'o U.K.",
    'Orch Bassoon',
    'Bassoon III',
    'BassFoons',
    'Cl/Bsn Usn',
    'Cl/Bsn 8va',
    'Fl/Ob Usn',
    'Fl/EH 8va',
    'Fl/Bsn 8va',
    'BsCl/Bsn 8vb',
    'BsCl/Bsn Usn',
    'Cl/Hrn/Bsn 1',
    'Cl/Hrn/Bsn 2',
    'Ob/Hrns/Bsns',
    'Ob/Bsn 8va',
    'Ob/EH Usn',
    'Ob/EH 8va',
    'EH/Bsn Usn',
    'EH/Bsn 8va',
    'EH/Cl Usn',
    'EH/Bs Cl 8va',
    'Ob/Cl Usn',
    'Ob/BsCl va',
    'Hrns/Bsns',
    'Really Reeds',
    'Reed Duet',
    'Multi Reeds',
    'Medieval Rds',
    'ScottishPIPE',
    'Hill&Sheeps',
    'HilndChr SRX',
    'Solo Fr.Horn',
    'SoloF.HrnSRX',
    'HrnAccompSRX',
    'Orch Hrns Sw',
    'Hornz Stereo',
    'Orch Hrns ff',
    'FizzHorns ff',
    'Fr.Horns SRX',
    'Dynamic Hrns',
    'Horn Sect /',
    'Fr.HrnSfzSRX',
    'MuteFr.Horns',
    'F.Horn Rip',
    'Trumpet Plus',
    'Natural Tmpt',
    'Real Tp SRX',
    'El Bono SRX',
    'Coronet',
    'Flugelhorn',
    'Mute Tp SRX',
    'HrmnMute SRX',
    'WahMute /Mod',
    'Trumpeters',
    'Tp Ens SRX',
    'Trumps fff!!',
    'Softy Bones',
    'Bone Fluegal',
    'Natural Tbn',
    'Trombone SRX',
    'SoloTb SRX 1',
    'SoloTb SRX 2',
    'Bs Tb',
    'Tbn One',
    'Bone Boys',
    'Bones sectn',
    'BigBones SRX',
    'BsBoneSctSRX',
    'Noblesse',
    'Brass Choral',
    'BrassEns/Mod',
    'Small Brass',
    'Brass Orche',
    'Switch Fall',
    '4-Pc Brs Scn',
    'BiggieBrsSRX',
    'SoloTuba SRX',
    'Tuba sfz/Mod',
    'Tuba SRX',
    'Medieval Brs',
    'No Name',
    'Full Brass',
    'Brass ff',
    'Brass Sect /',
    'Multi Sax',
    'St.EuroPiano',
    'JoyoClassics',
    'Empathy',
    'Piano & Strs',
    'Pno Concerto',
    'Song Wish',
    'HpsFrntSRX 1',
    'HpsFrntSRX 2',
    'HpsFrntSRX 3',
    'HpsBackSRX 1',
    'HpsBackSRX 2',
    'HpsBackSRX 3',
    'Hps F/B SRX',
    'Hps F4/B SRX',
    'Hps F/B/B4 S',
    'HpsLuteSRX 1',
    'HpsLute 2',
    'HpsLute 3',
    'FullHarpsi 1',
    'FullHarpsi 2',
    'Continuo Pdl',
    'Celesta SRX',
    'MusicBellSRX',
    'Water Mallet',
    'Newborn',
    'Victoriana 1',
    'St.M.Box SRX',
    'Victoriana 2',
    'ChurchBellS1',
    'BlfryChm SRX',
    'ChurchBellS2',
    'Tub.Bells S1',
    'Tub.Bells S2',
    'BsMarimbSRX1',
    'BsMarimbSRX2',
    'MultiMallets',
    'Glocken',
    'Glockeneste',
    'GlocknlstSRX',
    'Clear Glock',
    'Xylorimba',
    'Xylophone S1',
    'Xylophone S2',
    'Mallet Stack',
    'OrgFlutes S1',
    'OrgFlutes S2',
    'OrgFlutes S3',
    "OrgFlute 8'S",
    'Psyche Pipes',
    'ChrchPipes S',
    'Organ&Recdr',
    'Early Harmn',
    'CathedralSRX',
    'Harmonium',
    'ChurchOrgSRX',
    'OrganChrdSRX',
    'Musaccordion',
    'Mystery Pad',
    'Psychedelic1',
    'Psychedelic2',
    'Eylsium m7^',
    'Eylsium 9th^',
    'Eylsium +7^',
    'Eylsium b9^',
    'Vln RunUp Mj',
    'Vln RunUp Mn',
    'Vln RunDn Mj',
    'Vln RunDn Mn',
    'Maj/MinHarps',
    '9th/b9 Harps',
    'Harp m7 SRX',
    'Harp 9th SRX',
    'Harp +7 SRX',
    'Harp b9 SRX',
    'Harpm7SclSRX',
    'Harp9thScrlS',
    'Harp+7SclSRX',
    'Harpb9SclSRX',
    'Cluster Gong',
    'Sus.Perc Hit',
    'Prc Ens6-Maj',
    'Prc Ens7-Min',
    'Prc Ens8-Dim',
    'Cluster SRX',
    'HorrorClustr',
    'Hell Section',
    'Legettimare',
    'Limbus SRX',
    'Backword',
    'Dreamseq SRX',
    'Midnight SRX',
    'Colombus SRX',
    'Once Upon A',
    'Desert Dream',
    'AncientTimes',
    'Tension SRX',
    'Wreck',
    'Eclipse SRX',
    'PulsingVox S',
    'SynthStr.Pad',
    'Meditate PAD',
    'Choir',
    'Angelic Pad',
    'BoysChoirSRX',
    'Sing! /Mod',
    'SmockyVoices',
    'Smooth Choir',
    'X. Vox SRX',
    'RealChoirSRX',
    'StChrMm/Ah S',
    'Mmms & Aaahs',
    'Choir /Mod',
    'Close Mouths',
    'Voice Stax',
    'MorphieChoir',
    'Morph4Choir',
    'th Movemnt',
    'Matins',
    'Quartet II 5',
    'Scat /',
    'Scatmen! SRX',
    'The Voices',
    'VocalCollect',
    'GregorianCho',
    'Soprano&co.',
    'Tenor solo',
    'ClarsahHarpS',
    'Heavens Harp',
    'C.Hrp/padSRX',
    'PhaseClarsah',
    'ClearHarpSRX',
    'Nails Harp',
    'Harp SRX',
    'Natural Harp',
    'Warm Harp',
    'Bousouk&Harp',
    'Etheral Lute',
    'DelicateCOMB',
    'St.CymblnSRX',
    'CymblnDuoSRX',
    'Bohemian SRX',
    'Bousouki Pic',
    'Bousouki',
    'PulcinelaSRX',
    'SN Roll SRX/',
    'Perc Ens 1^',
    'Perc Ens 2^',
    'Perc Ens 3^',
    'Perc Ens 4^',
    'Perc Ens 5^',
    'Orch Percs',
    'BodhranSplit',
    'BodhranVel S',
    'CrazyBodhrnS',
    'BodhranMenuS',
    'Perc Mix SRX',
    'MassiveTimpa',
    '4-way Timps',
    'DynaTimpsSRX',
    'TimpaniRoll1',
    'TimpaniRoll2',
    'MultiTimpani',
    'Roll > Klang',
    'Timpani /',
    'Big Orc.Perc',
    'WindChimeSRX',
    'FingerCymSRX',
    'ConcertBDSRX',
    'BD Roll SRX/',
    'Tam Tam SRX',
    'Piatti!! SRX',
    'SleighBellsS',
    'SlapstickS /',
    'TambourineS/',
    'CastanetsS /'
  ]
};
